In [1]:
%load_ext autoreload
%autoreload 2

# `import`

In [2]:
import os
import warnings
import torch

import numpy as np
import pandas as pd
import tensorflow as tf

from collections import defaultdict

from sb3_contrib import MaskablePPO

from medical_rl.libs.RL import Model
from medical_rl.libs.envs import get_env
from medical_rl.libs.cluster import get_data_clustered_completed
from medical_rl.data_formatters.amsterdam import AmsterdamFormatter

from dice_rl_TU_Vienna.wrappers import AbsorbingWrapper, LoopingWrapper
from dice_rl_TU_Vienna.dataset import get_dataset_from_df, get_dataset_from_env
from dice_rl_TU_Vienna.plugins.stable_baselines3.policy import get_probs_MaskablePPO

from plugins.medical_rl.sepsis_amsterdam.config import *

/Users/richardweiss/Documents/.venvs/dice_rl_TU_Vienna/lib/python3.11/site-packages/torch/utils/_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(

In [ ]:
pd.set_option('display.max_colwidth', 36)

# Prepare

In [3]:
def RL_split_to_dataset(RL_split, tabular):

    id, t, obs, act, rew = RL_split

    id  = np.array(id,  dtype=np.int64)
    t   = np.array(t,   dtype=np.int64)
    obs = np.array(obs, dtype=np.int64 if tabular else np.float32)
    act = np.array(act, dtype=np.int64)
    rew = np.array(rew, dtype=np.float32)

    obs_init = []
    obs_next = []

    i_init = 0
    for i in range(len(id)):

        if i > 0 and id[i] != id[i-1]:
            i_init = i

        if i == len(id) - 1 or id[i+1] != id[i]:
            i_next = i
        else:
            i_next = i+1

        obs_init.append( obs[i_init] )
        obs_next.append( obs[i_next] )

    obs_init = np.array(obs_init)
    obs_next = np.array(obs_next)

    return pd.DataFrame({
        "id": list(id),
        "t": list(t),
        "obs_init": list(obs_init),
        "obs": list(obs),
        "act": list(act),
        "rew": list(rew),
        "obs_next": list(obs_next),
    })

# Continuous

In [ ]:
seed = 42

In [219]:
def create_dataset_continuous():
    _, _, test_, bounds_ = AmsterdamFormatter() \
        .load_random_split_and_bounds(dir_split, seed)

    test_.sort_values(["ID", "Length of Stay"], inplace=True)
    RL_split_test = AmsterdamFormatter().RL_split(test_)
    test = RL_split_to_dataset(RL_split_test, tabular=False)

    obs_min = np.array(bounds_[0])
    obs_max = np.array(bounds_[1])

    return test, obs_min, obs_max

In [220]:
test, obs_min, obs_max = create_dataset_continuous()

In [221]:
test

          id  t  ...  rew                                           obs_next
0         20  0  ...  0.0  [-0.0800016, -0.08865834, -0.08860586, -0.0254...
1         20  1  ...  0.0  [-0.0800016, -0.08865834, -0.08860586, -0.0254...
2         20  2  ...  0.0  [-0.0800016, -0.08865834, -0.08860586, -0.0254...
3         20  3  ...  0.0  [-0.0800016, -0.08865834, -0.08860586, -0.0254...
4         20  4  ...  0.0  [-0.0800016, -0.08865834, -0.08860586, -0.0254...
...      ... ..  ...  ...                                                ...
14571  23535  3  ...  1.0  [-0.0800016, -0.08865834, -0.08860586, -0.0254...
14572  23535  4  ...  1.0  [-0.0800016, -0.08865834, -0.08860586, -0.0254...
14573  23535  5  ...  1.0  [-0.0800016, -0.08865834, -0.08860586, -0.0254...
14574  23535  6  ...  1.0  [-0.0800016, -0.08865834, -0.08860586, -0.0254...
14575  23535  7  ...  1.0  [-0.0800016, -0.08865834, -0.08860586, -0.0254...

[14576 rows x 7 columns]

In [222]:
obs_min

array([-8.06915820e-01, -9.54015851e-01, -9.53790426e-01, -2.54084524e-02,
       -2.32830763e+00, -2.44670534e+00, -1.45127904e+00, -1.45634305e+00,
       -2.97194242e+00, -3.48733473e+00, -3.22874856e+00, -7.29413033e-01,
       -3.08796191e+00, -3.08928204e+00, -3.03649926e+00, -1.08392823e+00,
       -2.19888973e+00, -2.25506067e+00, -2.35733342e+00, -2.00814128e+00,
       -6.15756035e+00, -6.53796244e+00, -5.98751926e+00, -8.12110126e-01,
       -2.61270351e+01, -2.29396400e+01, -2.70833540e+00, -8.45425034e+00,
       -9.53036118e+00, -1.81086807e+01, -4.54230976e+00, -3.67017102e+00,
       -4.41145515e+00, -3.99905181e+00, -7.06714690e-01, -4.77863938e-01,
       -4.77305025e-01, -4.74949658e-01, -7.41412878e-01, -1.17235243e+00,
       -1.16939533e+00, -1.15859377e+00, -1.04782426e+00, -8.63174260e-01,
       -2.40820289e+00, -9.52082348e+00, -4.63353023e-02, -3.78860283e+00,
       -3.77877259e+00, -3.76478910e+00, -4.32487205e-02, -7.42801905e-01,
       -4.85994720e+00, -7.80608082e+00, -4.71839495e-02, -1.94620562e+00,
       -3.59345412e+00, -2.75349903e+00, -1.00415587e+00, -1.10821879e+00,
       -1.14049697e+00, -1.18284929e+00, -5.64071357e-01, -3.36050630e+00,
       -3.36050630e+00, -3.36050630e+00,  0.00000000e+00, -1.78177023e+00,
       -2.63522172e+00, -3.02552819e+00, -8.56090963e-01, -3.55314314e-02,
       -3.55303288e-02, -3.55292633e-02, -5.50895643e+00, -1.83581620e-01,
       -2.26875514e-01, -1.93393290e-01, -1.76160157e-01, -2.91009963e-01,
       -3.07688236e-01, -3.18200290e-01, -1.84086800e-01, -2.27874780e+00,
       -3.02083468e+00, -2.57567501e+00, -1.12813795e+00, -8.17834187e+00,
       -8.17556572e+00, -8.16753483e+00, -9.03221518e-02, -1.04616013e+01,
       -1.04616013e+01, -1.04616013e+01, -3.78641449e-02, -5.29186392e+00,
       -5.73906326e+00, -4.73980379e+00, -1.86346874e-01, -1.69378262e+01,
       -4.65805578e+00, -4.41035767e+01, -3.08572054e-01, -4.96249819e+00,
       -4.66725731e+00, -4.29626417e+00, -4.34029341e-01, -7.25996590e+00,
       -2.86308327e+01, -3.53951721e+01, -9.62077677e-01, -3.33899474e+00,
       -3.57710457e+00, -3.71765614e+00, -9.79677122e-03, -5.01324987e+00,
       -5.00841427e+00, -4.99831772e+00, -2.85352170e-02, -9.47036445e-01,
       -1.03930008e+00, -1.05834317e+00, -6.49953663e-01, -8.89832973e-02,
       -8.43996778e-02, -6.85402378e-02, -9.25584212e-02, -1.90000000e+01,
       -1.90000000e+01, -1.90000000e+01,  0.00000000e+00, -1.28522158e+00,
       -1.29942918e+00, -1.29060650e+00, -8.31801653e-01, -3.74819189e-01,
       -3.71078551e-01, -3.67159039e-01, -2.23462796e+00, -1.69319897e+01,
       -1.69674988e+01, -1.69676838e+01, -2.15084434e+00, -7.15083361e+00,
       -7.37936687e+00, -7.36868954e+00, -4.21329069e+00, -8.27718452e-02,
       -1.24796307e+00, -4.95824909e+00, -9.97292846e-02, -8.43439639e-01,
       -7.68151331e+00, -4.78676033e+01, -8.95808414e-02, -6.76395130e+00,
       -2.31452370e+01, -2.14822407e+01, -1.90461293e-01, -9.29418147e-01,
       -9.16560173e-01, -9.16304529e-01, -7.31199682e-02, -4.68080282e+00,
       -1.37990475e+01, -2.53613529e+01, -7.69328058e-01, -2.57231998e+01,
       -4.43504639e+01, -4.43504639e+01, -2.48892214e-02, -1.99578774e+00,
       -2.38156223e+00, -1.24971414e+00, -1.67597163e+00, -2.05126357e+00,
       -2.70510125e+00, -2.55365443e+00, -1.16673684e+00, -2.16948247e+00,
       -2.86512208e+00, -3.27024627e+00, -5.41437149e-01, -3.45802486e-01,
       -6.81373775e-01, -6.75405979e-01, -9.60106328e-02, -7.77658415e+00,
       -9.69930840e+00, -1.20210714e+01, -4.62343454e+00, -4.47822452e-01,
       -7.18827009e-01, -7.41441548e-01, -1.59148678e-01, -7.50997305e-01,
       -6.04152083e-01, -2.84954518e-01, -9.57863390e-01, -2.92718887e+00,
       -2.83756185e+00, -2.78898811e+00, -5.18779325e+00, -2.03206873e+00,
       -5.86123419e+00, -3.77449703e+00, -1.46375194e-01, -5.54890537e+00,
       -5.40770531e+00, -5.26774406e+00, -9.96078253e-01, -3.75033689e+00,
       -6.57310963e+00, -3.94640899e+00, -1.78797722e-01, -5.47335625e+00,
       -5.21668291e+00, -4.98719931e+00, -9.86756086e-01, -4.51958418e+00,
       -6.29521275e+00, -3.96570754e+00, -2.72345841e-01, -4.74249840e+00,
       -4.50498819e+00, -4.33115387e+00, -9.38890874e-01, -1.61851585e+00,
       -1.94192767e+00, -2.63493752e+00, -2.88199902e+00, -2.60975361e-01,
       -2.16639489e-01, -9.56084061e+00, -1.06103764e+01, -8.75149742e-02,
       -5.51771736e+01, -3.37559853e+01, -8.83310413e+00, -7.99549937e-01,
       -5.60008824e-01, -5.58068395e-01, -5.33924282e-01, -4.32770395e+00,
       -7.93437881e+01, -8.20649338e+01, -2.25568924e+01, -1.34809589e+00,
       -1.51718485e+00, -1.49551833e+00, -1.47510171e+00, -8.54948938e-01,
       -2.35689783e+00, -2.58576965e+00, -2.36979365e+00, -4.44492511e-02,
       -1.67383182e+00, -1.50726569e+00, -1.46057856e+00, -2.17201376e+00,
       -3.21458173e+00, -3.09007239e+00, -3.24794269e+00, -3.37522292e+00,
       -1.23717833e+00, -1.46405125e+00, -1.43231595e+00, -2.13025546e+00,
       -4.99080563e+00, -4.07025671e+00, -4.09021568e+00, -6.57141209e-02,
       -1.32839632e+00, -1.32517672e+00, -1.43224967e+00, -7.39378691e-01,
       -1.50103152e+00, -1.49142814e+00, -9.25668657e-01, -1.25993192e+00,
       -7.67816734e+00, -3.12934470e+00, -3.08731818e+00, -3.04504895e+00,
       -6.36989415e-01, -1.82449150e+00, -1.82776761e+00, -1.83045268e+00,
       -4.26480696e-02, -1.04434609e-01,  0.00000000e+00, -4.20163002e+01,
       -4.67293784e-02, -2.33135748e+00, -4.06357908e+00, -4.50624704e+00,
       -1.06608534e+00, -1.00651115e+02,  7.28000000e+02, -9.95272980e+01,
       -2.16815062e-02, -1.48802209e+00, -1.48474491e+00, -1.35374200e+00,
       -3.70563455e-02, -6.93542778e-01, -8.18431526e-02, -3.74847353e-02,
       -3.22635397e-02, -1.36441305e-01, -3.37151326e-02, -1.78695336e-01,
       -9.80581269e-02, -3.71836603e-01, -4.75990653e-01, -4.61997449e-01,
       -2.80533195e-01, -1.90043271e-01, -2.90260166e-01, -5.76969266e-01,
       -8.57090428e-02, -1.92506164e-01, -2.95091659e-01, -1.97454795e-01,
       -3.00736040e-01, -1.62213877e-01, -2.20604435e-01, -5.07222176e-01,
       -3.84288192e-01, -2.25349665e-01, -2.49517951e-02, -2.46122889e-02,
       -1.60867751e-01, -3.15893218e-02, -1.21019170e-01, -9.69805121e-02,
       -2.94235677e-01, -4.74155635e-01, -3.13581944e-01, -1.55290008e-01,
       -3.12243819e-01, -2.89008856e-01, -3.93194139e-01, -9.62433591e-02,
       -7.87413940e-02, -3.10176522e-01, -1.97383299e-01, -2.75928974e-01,
       -1.62117273e-01, -2.20691025e-01, -3.50649387e-01, -6.26690388e-01,
       -9.83115956e-02, -4.07214724e-02, -5.95556013e-02, -1.32881388e-01,
       -3.65375318e-02, -1.54320017e-01, -6.84934109e-02, -3.35891426e-01,
       -4.35091615e-01, -4.28386629e-01, -2.54415691e-01, -7.49172494e-02,
       -2.77414858e-01, -5.67019641e-01, -6.76125437e-02, -1.64723903e-01,
       -2.68129379e-01, -2.03935817e-01, -4.34157789e-01, -1.47973523e-01,
       -2.17688963e-01, -5.10301292e-01, -6.28516197e+00, -2.71663189e-01,
       -1.96912777e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00])

In [223]:
obs_max

array([ 5.69423790e+01,  2.74104805e+01,  2.74050369e+01,  2.41096640e+00,
        8.48044205e+00,  1.47043753e+01,  1.43512983e+01,  2.34378076e+00,
        2.12411346e+01,  2.77196846e+01,  2.83973942e+01,  1.25085926e+00,
        4.95312119e+00,  5.04160357e+00,  5.04312611e+00,  3.50155783e+00,
        3.08868542e+01,  3.29250221e+01,  3.44894981e+01, -2.00814128e+00,
        2.74480343e+01,  2.14069958e+01,  2.07772083e+01,  5.10954618e-01,
        8.80081081e+00,  1.09015923e+01,  1.79302856e-01,  1.64076187e+02,
        2.00921219e+02,  2.06600082e+02,  1.00391424e+00,  5.10706177e+01,
        4.57524920e+00,  5.58103991e+00,  4.78265643e-01,  2.65454044e+01,
        2.70125237e+01,  2.74020386e+01,  2.39406729e+00,  5.19698048e+00,
        5.49257851e+00,  5.34956837e+00, -5.68367660e-01,  9.14467087e+01,
        2.24091644e+02,  8.96394897e+02, -4.63353023e-02,  1.30696144e+01,
        1.30436869e+01,  1.30009518e+01, -4.32487205e-02,  7.78269434e+00,
        6.25319290e+01,  2.18146634e+00,  1.06671691e-01,  1.46859512e+01,
        2.23257961e+01,  1.97080898e+01, -9.23389614e-01,  1.56969824e+01,
        1.78252239e+01,  1.13902626e+01,  5.27258539e+00,  2.81011581e+01,
        2.81011581e+01,  2.81011581e+01,  0.00000000e+00,  2.10119724e+00,
        6.23745632e+00,  8.74369431e+00,  5.87125111e+00,  2.91534386e+01,
        2.91534386e+01,  2.91534386e+01, -5.50895643e+00,  5.49852638e+01,
        7.17274017e+01,  6.45217056e+01, -1.21497005e-01,  3.43456612e+01,
        3.58067169e+01,  3.58667946e+01,  2.05239430e-01,  2.89285980e+02,
        4.72231232e+02,  5.02649445e+02,  7.65155792e+00,  8.68973064e+00,
        8.68822098e+00,  8.68112659e+00, -9.03221518e-02,  2.43684273e+01,
        2.43684273e+01,  2.43684273e+01,  8.25622131e+02,  9.08070278e+00,
        1.32801390e+01,  1.40495453e+01,  5.89036793e-02,  9.54304218e+00,
        1.38338118e+01,  3.56082611e+01,  1.58197030e-01,  1.44770155e+01,
        1.43669586e+01,  1.40461807e+01, -4.34029341e-01,  9.92143707e+01,
        4.18384857e+02,  5.54384277e+02,  9.41713905e+00,  4.65795898e+01,
        5.36320343e+01,  5.98604164e+01, -9.79677122e-03,  1.98678875e+01,
        1.98560848e+01,  1.98207359e+01,  2.18185196e+02,  4.35507965e+01,
        5.38658981e+01,  6.26580200e+01,  2.13624716e+00,  9.40452957e+01,
        1.26229713e+02,  1.75076324e+02, -8.95343423e-02,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  2.00000000e+00,  2.72193794e+01,
        2.81935158e+01,  2.71267948e+01,  1.36786535e-01,  6.75634384e+01,
        6.76088181e+01,  6.76184692e+01,  2.24757118e+01,  8.29252720e+00,
        8.32817364e+00,  8.36157608e+00, -1.65630257e+00,  8.43681812e+00,
        8.44421101e+00,  8.44006157e+00,  1.65787673e+00,  7.41748123e+01,
        1.22292995e+01,  7.01904249e+00,  2.15376878e+00,  6.43598938e+01,
        1.44230509e+01,  9.71892548e+00,  3.43273431e-02,  5.26289978e+02,
        2.99263363e+01,  5.09942818e+00,  5.80680251e-01,  3.64133334e+00,
        3.64026284e+00,  3.64027286e+00,  4.61370945e+00,  9.66327362e+01,
        2.10799427e+01,  2.18883495e+01,  1.97419941e-01,  1.60614059e+02,
        2.30938919e+02,  2.30938919e+02,  4.88702822e+00,  7.00250473e+01,
        5.19924498e+00,  5.65238285e+00,  9.23804224e-01,  9.64911461e+00,
        1.60534496e+01,  8.03078175e+00,  7.09629536e-01,  8.38449287e+00,
        1.18033152e+01,  1.42528057e+01,  1.84893394e+00,  1.20461937e+02,
        7.97444439e+00,  8.64901447e+00,  1.37855506e+00,  1.44602402e+02,
        5.63911133e+01,  2.35563793e+01,  8.88098180e-01,  5.90954323e+01,
        8.20490189e+01,  8.84122772e+01,  1.54883873e+00,  7.50093307e+01,
        4.38511162e+01,  6.01967278e+01, -9.57863390e-01,  5.42773771e+00,
        5.61149979e+00,  5.59368181e+00,  2.39492702e+01,  4.74434423e+00,
        2.32378769e+01,  2.13633671e+01, -5.45882620e-03,  1.82669220e+01,
        2.03377647e+01,  2.12256336e+01,  3.69333839e+00,  6.18368292e+00,
        1.73862610e+01,  1.51545353e+01,  7.20370635e-02,  1.29714270e+01,
        1.42515469e+01,  1.48512478e+01,  4.66236734e+00,  3.53392363e+00,
        8.56203938e+00,  8.69418812e+00,  1.33801982e-01,  6.77092648e+00,
        7.53686619e+00,  7.87289667e+00,  6.45734978e+00,  1.42445526e+01,
        4.81249733e+01,  6.96763306e+01,  3.34651146e+01,  1.67453194e+00,
        4.67558002e+00,  3.93793166e-01,  5.01180530e-01,  9.18213308e-01,
        2.93527126e-01,  1.02420604e+00,  9.86259937e-01,  3.15995097e+00,
        2.63598576e+01,  2.63965950e+01,  2.63427238e+01,  1.00632830e+01,
        1.66529427e+01,  1.95564003e+01,  6.18239307e+00,  4.20221519e+00,
        6.35722685e+00,  6.72643375e+00,  6.37165642e+00,  5.88033080e-01,
        1.27468004e+01,  1.28180761e+01,  1.27932663e+01,  1.27508980e+02,
        1.23752375e+01,  1.16687002e+01,  9.95166588e+00, -2.17201376e+00,
        1.14904175e+01,  1.13854942e+01,  1.09861917e+01, -3.37522292e+00,
        1.62216454e+01,  8.58332348e+00,  8.54451942e+00, -2.13025546e+00,
        1.60138836e+01,  1.56824093e+01,  1.57780647e+01, -6.57141209e-02,
        7.72540617e+00,  7.36884689e+00,  7.43273306e+00,  3.36522508e+00,
        1.32446289e+01,  2.81742744e+01,  4.93413162e+01,  4.05314970e+00,
        2.16798363e+01,  1.35357580e+01,  1.36497269e+01,  1.35246162e+01,
        3.25694203e+00,  2.10183735e+01,  2.10609722e+01,  2.10967789e+01,
       -4.26480696e-02,  5.13802567e+01,  0.00000000e+00, -4.85582161e+00,
       -4.67293784e-02,  3.78022919e+01,  2.07865295e+01,  1.91149597e+01,
        6.73431206e+00,  4.80527461e+04,  7.42500000e+03, -5.90619354e+01,
        3.73877406e-01,  3.77884064e+01,  4.13378410e+01,  4.16694565e+01,
        2.46955037e+00,  7.17814016e+00,  9.92934799e+01,  5.18125725e+01,
        5.12065697e+01,  2.12343712e+01,  5.26877701e-01,  3.84482819e+02,
        5.25738373e+01,  5.07118645e+01,  6.66499901e+00,  3.21282125e+00,
        5.85025883e+00,  7.18693466e+01,  9.51179123e+00,  6.06979828e+01,
        7.24121475e+01,  3.65272942e+01,  1.50615215e+01,  1.89794121e+01,
        9.97412300e+00,  1.86151295e+01,  1.29792662e+01,  1.77790489e+01,
        4.80539274e+00,  1.29984465e+01,  6.02207031e+01,  6.39846725e+01,
        2.87157078e+01,  5.62991440e-01,  1.34643345e+01,  7.06224442e+01,
        8.38240337e+00,  7.70152760e+00,  4.60407686e+00,  1.84070778e+01,
        1.62781315e+01,  9.98916626e+00,  1.88427124e+01,  2.55209656e+01,
        3.44033265e+00,  1.73368607e+01,  1.89851685e+01,  5.11193275e+00,
        1.86286221e+01,  1.30923786e+01,  4.38043118e+00,  2.82996106e+00,
        1.90970728e+03,  4.93536110e+01,  4.08263321e+01,  2.24814873e+01,
        2.19612098e+00,  3.08884048e+01,  3.50367661e+01,  7.26962852e+00,
        9.95413780e+00,  3.32226706e+00,  9.36134720e+00,  2.66583443e+01,
        1.24174366e+01,  1.42371502e+01,  1.87414894e+01,  2.59050293e+01,
        2.25968647e+01,  1.69497046e+03,  3.45058990e+00,  2.95292263e+01,
        1.22674713e+01,  3.06915140e+00,  1.41417150e+01,  1.14214802e+01,
        3.78739643e+00,  5.00000000e+00,  2.00000000e+00,  3.00000000e+00,
        1.00000000e+00,  1.00000000e+00])

In [226]:
def get_probs_AmsterdamA2C(observation, model):
    o = observation
    o = list(o)
    o = tf.convert_to_tensor(o, tf.float32)

    l, _ = model(o)
    p = tf.nn.softmax(l, axis=1)
    p = np.array(p)

    return p


def add_probs(df, model):
    df = df.copy(deep=False)
    df["probs_init"] = list( get_probs_AmsterdamA2C(df["obs_init"], model) )
    df["probs_next"] = list( get_probs_AmsterdamA2C(df["obs_next"], model) )
    return df

In [224]:
model = Model(5, 1024)
model.load_weights( os.path.join(dir_policy["continuous"], f"policy.h5"))

In [227]:
dataset = add_probs(test, model)

In [231]:
dataset

          id  ...                                         probs_next
0         20  ...  [4.6153204e-07, 0.41843063, 0.09803962, 0.2416...
1         20  ...  [1.3341968e-18, 0.99022615, 0.0011949288, 0.00...
2         20  ...  [4.3437872e-23, 0.99479574, 5.7580583e-06, 0.0...
3         20  ...  [9.325621e-10, 0.00401068, 0.008864737, 0.9811...
4         20  ...  [4.656923e-15, 6.592461e-05, 0.0002901405, 0.9...
...      ...  ...                                                ...
14571  23535  ...  [4.4590848e-10, 4.408491e-09, 0.0012431995, 0....
14572  23535  ...  [6.259185e-07, 1.6154662e-07, 0.01574939, 0.98...
14573  23535  ...  [1.4885998e-09, 6.200223e-07, 0.010555137, 0.9...
14574  23535  ...  [1.3618055e-17, 1.7175033e-06, 0.6644643, 0.33...
14575  23535  ...  [1.3618055e-17, 1.7175033e-06, 0.6644643, 0.33...

[14576 rows x 9 columns]

In [ ]:
# dataset.to_parquet( os.path.join(dir_policy["continuous"], f"dataset.parquet") )
# np.save( os.path.join(dir_policy["continuous"], f"obs_min.npy"), obs_min, )
# np.save( os.path.join(dir_policy["continuous"], f"obs_max.npy"), obs_max, )

In [32]:
[ i for i, b in enumerate(obs_min < obs_max) if not b ]

[19, 46, 50, 66, 74, 90, 106, 114, 198, 259, 263, 267, 271, 288, 290, 292]

In [33]:
[ i for i, b in enumerate(obs_min <= obs_max) if not b ]

[]

# Tabular

In [4]:
# ---------------------------------------------------------------- #
# clustering

seed = 42
n_clusters = 256
n_init = 10

n_obs = n_clusters + 2
n_act = 5

# ---------------------------------------------------------------- #
# dataset

n_trajectories = 10_000
max_trajectory_length = None
# seed

# ---------------------------------------------------------------- #

In [ ]:
def dataset_clustered_to_RL_split(df):
    return df["id"], df["t"], df["obs"], df["act"], df["rew"]


def create_datasets_tabular(hyperparameters):
    train, _, test, _ = AmsterdamFormatter() \
        .load_random_split_and_bounds(dir_split, seed)

    train_clustered = get_data_clustered_completed(
        data=train,
        features=hyperparameters["features"],
        n_clusters=hyperparameters["n_clusters"],
        n_init=hyperparameters["n_init"],
        seed=hyperparameters["seed"],
        path=dir_clustering,
    )

    test_clustered = get_data_clustered_completed(
        data=test,
        features=hyperparameters["features"],
        n_clusters=hyperparameters["n_clusters"],
        n_init=hyperparameters["n_init"],
        seed=hyperparameters["seed"],
        path=dir_clustering,
    )

    RL_split_train = dataset_clustered_to_RL_split(train_clustered)
    RL_split_test  = dataset_clustered_to_RL_split(test_clustered)

    train_clustered = RL_split_to_dataset(RL_split_train, tabular=True)
    test_clustered  = RL_split_to_dataset(RL_split_test,  tabular=True)

    return train_clustered, test_clustered

In [129]:
train_clustered, test_clustered = create_datasets_tabular(
    hyperparameters={
        "seed": seed,
        "features": [
            'RRmean (ABP) mean',
            'RRmean (NIBP) mean',
            'Leukozyten max',
            'Heartrate mean',
            'Heartrate std',
            'Glucose mean',
            'Respiratory Rate resp min',
            'Noradrenaline (Norepinefrine) max',
            'Thrombozyten max',
            'PTT max',
            'PEEP max',
            'Fluid balance',
            'SOFA score',
            'Age',
            'Gender',
            'Antibiotics',
        ],
        "n_clusters": n_clusters,
        "n_init": n_init,
    },
)

Trying to load data/medical_rl/sepsis_amsterdam/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/kmeans_model.pkl
Trying to load data/medical_rl/sepsis_amsterdam/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/kmeans_model.pkl

In [ ]:
# train_clustered.to_parquet( os.path.join(dir_clustering, "train.parquet") )
# test_clustered .to_parquet( os.path.join(dir_clustering, "test.parquet") )

In [133]:
test_clustered.head(50)

    id   t  obs_init  obs  act  rew  obs_next
0   20   0        58   58    1  0.0       179
1   20   1        58  179    1  0.0        17
2   20   2        58   17    1  0.0        17
3   20   3        58   17    1  0.0        17
4   20   4        58   17    1  0.0        17
5   20   5        58   17    1  0.0        17
6   20   6        58   17    1  0.0       195
7   20   7        58  195    0  0.0       256
8   20   8        58  256    4  0.0       256
9   25   0       254  254    2  0.0       254
10  25   1       254  254    2  0.0       254
11  25   2       254  254    2  1.0       257
12  25   3       254  257    3  0.0       257
13  44   0         2    2    0  0.0       256
14  44   1         2  256    0  0.0       256
15  47   0       181  181    0  0.0       181
16  47   1       181  181    0  0.0       188
17  47   2       181  188    3  0.0        17
18  47   3       181   17    3  0.0        17
19  47   4       181   17    3  0.0       256
20  47   5       181  256    4  0.0       256
21  50   0       116  116    0  0.0        41
22  50   1       116   41    2  0.0        41
23  50   2       116   41    3  0.0        41
24  50   3       116   41    3  0.0        41
25  50   4       116   41    3  0.0        41
26  50   5       116   41    3  0.0        41
27  50   6       116   41    3  0.0        17
28  50   7       116   17    2  0.0        41
29  50   8       116   41    1  0.0        41
30  50   9       116   41    1  0.0        41
31  50  10       116   41    1  0.0        41
32  50  11       116   41    1  0.0         2
33  50  12       116    2    1  0.0         2
34  50  13       116    2    0  0.0       181
35  50  14       116  181    0  0.0       181
36  50  15       116  181    0  0.0       181
37  50  16       116  181    0  0.0       181
38  50  17       116  181    0  0.0       181
39  50  18       116  181    0  0.0         2
40  50  19       116    2    0  0.0         2
41  50  20       116    2    0  0.0       181
42  50  21       116  181    0  0.0         2
43  50  22       116    2    0  0.0         2
44  50  23       116    2    3  0.0         2
45  50  24       116    2    3  0.0         2
46  50  25       116    2    3  0.0        41
47  50  26       116   41    3  0.0        17
48  50  27       116   17    2  0.0       181
49  50  28       116  181    1  0.0         2

In [9]:
env_train, action_mask_train = get_env(
    n_clusters=n_clusters,
    data_clustered=train_clustered, )

env_test, action_mask_test = get_env(
    n_clusters=n_clusters,
    data_clustered=test_clustered, )

env_test_absorbing = AbsorbingWrapper(env_test)
env_test_looping   = LoopingWrapper  (env_test)

In [10]:
model = {
    name: MaskablePPO.load(
        os.path.join(dir_policy["tabular"][name], "policy.zip")
    )
        for name in names[1:]
}

def get_act_(obs, model):
    with warnings.catch_warnings(action="ignore", category=UserWarning):
        act, _ = model.predict(obs, action_masks=action_mask_test[obs])
        act = int(act)
        return act

get_act_exploratory = lambda obs: get_act_(obs, model["exploratory"])
get_act_evaluation  = lambda obs: get_act_(obs, model["evaluation"])

get_act = {
    "exploratory": get_act_exploratory,
    "evaluation": get_act_evaluation,
}

In [134]:
def get_processing(processors=None):
    if processors is None: processors = []

    def processing(df):
        df = df.copy(deep=False)
        for processor in processors:
            df = processor(df)
        return df

    return processing

def get_probs_behavior_dict(df):

    mults = defaultdict(lambda: [ 0 for act in range(n_act) ] )

    for i in range( len(df) ):
        obs = df.loc[i, "obs"]
        act = df.loc[i, "act"]
        mults[obs][act] += 1 # type: ignore

    probs = {
        k: v / np.sum(v)
        for k, v in mults.items()
    }

    return probs


def add_probs_evaluation(df):
    df = df.copy(deep=False)
    df["probs_init"] = list( get_probs_MaskablePPO(df["obs_init"], model["evaluation"], action_mask_test) )
    df["probs"]      = list( get_probs_MaskablePPO(df["obs"],      model["evaluation"], action_mask_test) )
    df["probs_next"] = list( get_probs_MaskablePPO(df["obs_next"], model["evaluation"], action_mask_test) )
    return df

def add_probs_behavior_original(df):
    df = df.copy(deep=False)
    probs_behavior_dict = get_probs_behavior_dict(df)
    df["probs_init_behavior"] = df["obs_init"].map(probs_behavior_dict)
    df["probs_behavior"]      = df["obs"]     .map(probs_behavior_dict)
    df["probs_next_behavior"] = df["obs_next"].map(probs_behavior_dict)
    return df

def add_probs_behavior_exploratory(df):
    df = df.copy(deep=False)
    df["probs_init_behavior"] = list( get_probs_MaskablePPO(df["obs_init"], model["exploratory"], action_mask_test) )
    df["probs_behavior"]      = list( get_probs_MaskablePPO(df["obs"],      model["exploratory"], action_mask_test) )
    df["probs_next_behavior"] = list( get_probs_MaskablePPO(df["obs_next"], model["exploratory"], action_mask_test) )
    return df


def normalize_timesteps(df, check_sorted=True):
    df = df.copy(deep=False)
    for id in df["id"].unique():
        f = df["id"] == id
        if check_sorted: assert np.all( np.diff(df.loc[f, "t"]) >= 0 )
        df.loc[f, "t"] = np.arange( len(df[f]) )

    return df


def reorder_columns(df, behavior):
    df = df.copy(deep=False)

    column_names = [ "id", "t", "obs_init", "obs", "act", "rew", "obs_next", "probs_init", "probs", "probs_next", ]
    if behavior:
        column_names += [ "probs_init_behavior", "probs_behavior", "probs_next_behavior", ]

    return df[column_names]


def handle_trajectory_ends(df, insert_row, behavior):

    uniform = np.ones(n_act) / n_act

    df = reorder_columns(df, behavior)

    df_parts = []

    for i, id in enumerate(df["id"].unique()):
        df_part = df[df["id"] == id].reset_index(drop=True)

        if insert_row:
            t = len(df_part)
            obs_init = df_part.loc[t-1, "obs_init"]
            obs = df_part.loc[t-1, "obs_next"]
            act = np.random.choice( range(n_act) )
            rew = 0
            obs_next = obs
            probs_init = df_part.loc[t-1, "probs_init"]
            probs = df_part.loc[t-1, "probs_next"]
            probs_next = probs

            row =  [ id, t, obs_init, obs, act, rew, obs_next, probs_init, probs, probs_next, ]

            if behavior:
                probs_init_behavior = df_part.loc[t-1, "probs_init_behavior"]
                probs_behavior = df_part.loc[t-1, "probs_next_behavior"]
                probs_next_behavior = probs_behavior

                row += [ probs_init_behavior, probs_behavior, probs_next_behavior, ]

            df_part.loc[len(df_part)] = row

        l = len(df_part)

        df_part.at[l-2, "probs_next"] = uniform
        df_part.at[l-1, "probs"]      = uniform
        df_part.at[l-1, "probs_next"] = uniform

        if behavior:
            df_part.at[l-2, "probs_next_behavior"] = uniform
            df_part.at[l-1, "probs_behavior"]      = uniform
            df_part.at[l-1, "probs_next_behavior"] = uniform

        df_parts.append(df_part)

    return pd.concat(df_parts).reset_index(drop=True)


handle_trajectory_ends_original    = lambda df: handle_trajectory_ends(df, insert_row=False, behavior=True)
handle_trajectory_ends_exploratory = lambda df: handle_trajectory_ends(df, insert_row=True,  behavior=True)
handle_trajectory_ends_evaluation  = lambda df: handle_trajectory_ends(df, insert_row=True,  behavior=False)

def cast_probs(df):
    df = df.copy(deep=False)
    cast_array = lambda x: np.array(x, dtype=np.float32)

    for column in df.columns:
        if "probs" not in column: continue

        df[column] = df[column].apply(cast_array) # type: ignore

    return df


postprocessing = {
    "original": get_processing([
        add_probs_evaluation,
        add_probs_behavior_original,
        normalize_timesteps,
        handle_trajectory_ends_original,
        cast_probs,
    ]),
    "exploratory": get_processing([
        add_probs_evaluation,
        add_probs_behavior_exploratory,
        normalize_timesteps,
        handle_trajectory_ends_exploratory,
        cast_probs,
    ]),
    "evaluation": get_processing([
        add_probs_evaluation,
        normalize_timesteps,
        handle_trajectory_ends_evaluation,
        cast_probs,
    ]),
}

In [135]:
dataset = {}
id_dataset = {}

name = "original"
x, y = get_dataset_from_df(
    dir=dir_clustering,
    df=test_clustered,
    hyperparameters={
        "evaluation_policy": {
            "id": id_policy["tabular"]["evaluation"],
        },
    },
    postprocessing=postprocessing[name],
    verbosity=1,
)
dataset[name] = x
id_dataset[name] = y

for name in names[1:]:

    x, y = get_dataset_from_env(
        dir=dir_policy["tabular"][name],
        env=env_test,
        get_act=get_act[name],
        hyperparameters={
            "n_trajectories": n_trajectories,
            "max_trajectory_length": max_trajectory_length,
            "seed": seed,
            "evaluation_policy": {
                "id": id_policy["tabular"]["evaluation"],
            },
        },
        postprocessing=postprocessing[name],
        verbosity=1,
    )

    dataset[name] = x
    id_dataset[name] = y

trying to find id_dataset in data/medical_rl/sepsis_amsterdam/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/dataset.json
trying to load dataset from data/medical_rl/sepsis_amsterdam/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/2025-03-22T18:29:07.873471/dataset.parquet
trying to find id_dataset in data/medical_rl/sepsis_amsterdam/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/2025-01-31T10:25:32.802016/dataset.json
trying to load dataset from data/medical_rl/sepsis_amsterdam/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/2025-01-31T10:25:32.802016/2025-03-22T18:30:01.187051/dataset.parquet
failed to load
creating dataset from environment

100%|██████████| 10000/10000 [00:42<00:00, 236.81it/s]

removing dataset hyperparameters from data/medical_rl/sepsis_amsterdam/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/2025-01-31T10:25:32.802016/dataset.json
saving dataset
saved data/medical_rl/sepsis_amsterdam/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/2025-01-31T10:25:32.802016/2025-03-22T18:46:50.582092/dataset.parquet
trying to find id_dataset in data/medical_rl/sepsis_amsterdam/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/2025-01-31T10:27:51.724072/dataset.json
trying to load dataset from data/medical_rl/sepsis_amsterdam/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/2025-01-31T10:27:51.724072/2025-03-22T18:31:04.173070/dataset.parquet
failed to load
creating dataset from environment

100%|██████████| 10000/10000 [00:52<00:00, 189.97it/s]

removing dataset hyperparameters from data/medical_rl/sepsis_amsterdam/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/2025-01-31T10:27:51.724072/dataset.json
saving dataset
saved data/medical_rl/sepsis_amsterdam/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/2025-01-31T10:27:51.724072/2025-03-22T18:47:53.614328/dataset.parquet

In [136]:
for k, v in dataset.items():
    print(f"{k=}")
    display(v.head(50))

k='original'

    id   t  obs_init  obs  act  rew  obs_next                           probs_init                                probs                           probs_next                  probs_init_behavior                       probs_behavior                  probs_next_behavior
0   20   0        58   58    1  0.0       179  [0.0011493295, 5.6734436e-05, 0....  [0.0011493295, 5.6734436e-05, 0....  [0.18146195, 0.025168937, 0.0182...  [0.6721915, 0.09208103, 0.082872...  [0.6721915, 0.09208103, 0.082872...  [0.61876833, 0.17302053, 0.05571...
1   20   1        58  179    1  0.0        17  [0.0011493295, 5.6734436e-05, 0....  [0.18146195, 0.025168937, 0.0182...  [0.00037134442, 0.026493562, 0.0...  [0.6721915, 0.09208103, 0.082872...  [0.61876833, 0.17302053, 0.05571...  [0.6468144, 0.1565097, 0.0484764...
2   20   2        58   17    1  0.0        17  [0.0011493295, 5.6734436e-05, 0....  [0.00037134442, 0.026493562, 0.0...  [0.00037134442, 0.026493562, 0.0...  [0.6721915, 0.09208103, 0.082872...  [0.6468144, 0.1565097, 0.0484764...  [0.6468144, 0.1565097, 0.0484764...
3   20   3        58   17    1  0.0        17  [0.0011493295, 5.6734436e-05, 0....  [0.00037134442, 0.026493562, 0.0...  [0.00037134442, 0.026493562, 0.0...  [0.6721915, 0.09208103, 0.082872...  [0.6468144, 0.1565097, 0.0484764...  [0.6468144, 0.1565097, 0.0484764...
4   20   4        58   17    1  0.0        17  [0.0011493295, 5.6734436e-05, 0....  [0.00037134442, 0.026493562, 0.0...  [0.00037134442, 0.026493562, 0.0...  [0.6721915, 0.09208103, 0.082872...  [0.6468144, 0.1565097, 0.0484764...  [0.6468144, 0.1565097, 0.0484764...
5   20   5        58   17    1  0.0        17  [0.0011493295, 5.6734436e-05, 0....  [0.00037134442, 0.026493562, 0.0...  [0.00037134442, 0.026493562, 0.0...  [0.6721915, 0.09208103, 0.082872...  [0.6468144, 0.1565097, 0.0484764...  [0.6468144, 0.1565097, 0.0484764...
6   20   6        58   17    1  0.0       195  [0.0011493295, 5.6734436e-05, 0....  [0.00037134442, 0.026493562, 0.0...  [0.02480495, 0.7613253, 0.104794...  [0.6721915, 0.09208103, 0.082872...  [0.6468144, 0.1565097, 0.0484764...  [0.8657845, 0.060491495, 0.03780...
7   20   7        58  195    0  0.0       256  [0.0011493295, 5.6734436e-05, 0....  [0.02480495, 0.7613253, 0.104794...            [0.2, 0.2, 0.2, 0.2, 0.2]  [0.6721915, 0.09208103, 0.082872...  [0.8657845, 0.060491495, 0.03780...            [0.2, 0.2, 0.2, 0.2, 0.2]
8   20   8        58  256    0  0.0       256  [0.0011493295, 5.6734436e-05, 0....            [0.2, 0.2, 0.2, 0.2, 0.2]            [0.2, 0.2, 0.2, 0.2, 0.2]  [0.6721915, 0.09208103, 0.082872...            [0.2, 0.2, 0.2, 0.2, 0.2]            [0.2, 0.2, 0.2, 0.2, 0.2]
9   25   0       254  254    2  0.0       254  [0.23725273, 0.742851, 0.0198962...  [0.23725273, 0.742851, 0.0198962...  [0.23725273, 0.742851, 0.0198962...  [0.5714286, 0.21428572, 0.214285...  [0.5714286, 0.21428572, 0.214285...  [0.5714286, 0.21428572, 0.214285...
10  25   1       254  254    2  0.0       254  [0.23725273, 0.742851, 0.0198962...  [0.23725273, 0.742851, 0.0198962...  [0.23725273, 0.742851, 0.0198962...  [0.5714286, 0.21428572, 0.214285...  [0.5714286, 0.21428572, 0.214285...  [0.5714286, 0.21428572, 0.214285...
11  25   2       254  254    2  1.0       257  [0.23725273, 0.742851, 0.0198962...  [0.23725273, 0.742851, 0.0198962...            [0.2, 0.2, 0.2, 0.2, 0.2]  [0.5714286, 0.21428572, 0.214285...  [0.5714286, 0.21428572, 0.214285...            [0.2, 0.2, 0.2, 0.2, 0.2]
12  25   3       254  257    3  0.0       257  [0.23725273, 0.742851, 0.0198962...            [0.2, 0.2, 0.2, 0.2, 0.2]            [0.2, 0.2, 0.2, 0.2, 0.2]  [0.5714286, 0.21428572, 0.214285...            [0.2, 0.2, 0.2, 0.2, 0.2]            [0.2, 0.2, 0.2, 0.2, 0.2]
13  44   0         2    2    0  0.0       256  [0.0014877882, 0.41098294, 0.481...  [0.0014877882, 0.41098294, 0.481...            [0.2, 0.2, 0.2, 0.2, 0.2]  [0.34615386, 0.21794872, 0.21367...  [0.34615386, 0.21794872, 0.21367...            [0.2, 0.2, 0.2, 0.2, 0.2]
14  44   1         2  256    4  0.0       256  [0.0014877882, 0.41098294, 0.481...            [0.2, 0.2, 0.2, 0.2, 0.2]            [0.2, 0.2, 0.2, 0.2, 0.2]  [0.34615386, 0.21794872, 0.21367...            [0.2, 0.2, 0.2, 0.2, 0.2]            [0.2, 0.2, 0.2, 0.2, 0.2]
15  47   0       181  181    0  0.0       181  [0.5756498, 0.02867316, 0.242340...  [0.5756498, 0.02867316, 0.242340...  [0.5756498, 0.02867316, 0.242340...  [0.8857143, 0.057142857, 0.03238...  [0.8857143, 0.057142857, 0.03238...  [0.8857143, 0.057142857, 0.03238...
16  47   1       181  181    0  0.0       188  [0.5756498, 0.02867316, 0.242340...  [0.5756498, 0.02867316, 0.242340...  [0.001137101, 0.014667103, 0.158...  [0.8857143, 0.057142857, 0.03238...  [0.8857143, 0.057142857, 0.03238...  [0.25, 0.09375, 0.125, 0.46875, ...
17  47   2       181  188    3  0.0        17  [0.5756498, 0.02867316, 0.242340...  [0.001137101, 0.014667103, 0.158...  [0.00037134442, 0.026493562, 0.0...  [0.8857143, 0.057142857, 0.03238...  [0.25, 0.09375, 0.125, 0.46875, ...  [0.6468144, 0.1565097, 0.0484764...
18  47   3       181   17    3  0.0        17  [0.5756498, 0.02867316, 0.242340...  [0.00037134442, 0.026493562, 0.0...  [0.00037134442, 0.026493562, 0.0...  [0.8857143, 0.057142857, 0.03238...  [0.6468144, 0.1565097, 0.0484764...  [0.6468144, 0.1565097, 0.0484764...
19  47   4       181   17    3  0.0       256  [0.5756498, 0.02867316, 0.242340...  [0.00037134442, 0.026493562, 0.0...            [0.2, 0.2, 0.2, 0.2, 0.2]  [0.8857143, 0.057142857, 0.03238...  [0.6468144, 0.1565097, 0.0484764...            [0.2, 0.2, 0.2, 0.2, 0.2]
20  47   5       181  256    3  0.0       256  [0.5756498, 0.02867316, 0.242340...            [0.2, 0.2, 0.2, 0.2, 0.2]            [0.2, 0.2, 0.2, 0.2, 0.2]  [0.8857143, 0.057142857, 0.03238...            [0.2, 0.2, 0.2, 0.2, 0.2]            [0.2, 0.2, 0.2, 0.2, 0.2]
21  50   0       116  116    0  0.0        41  [0.0042242263, 0.0015765585, 0.0...  [0.0042242263, 0.0015765585, 0.0...  [0.051144704, 0.9260171, 0.00950...  [0.15384616, 0.23076923, 0.07692...  [0.15384616, 0.23076923, 0.07692...  [0.42985076, 0.1522388, 0.089552...
22  50   1       116   41    2  0.0        41  [0.0042242263, 0.0015765585, 0.0...  [0.051144704, 0.9260171, 0.00950...  [0.051144704, 0.9260171, 0.00950...  [0.15384616, 0.23076923, 0.07692...  [0.42985076, 0.1522388, 0.089552...  [0.42985076, 0.1522388, 0.089552...
23  50   2       116   41    3  0.0        41  [0.0042242263, 0.0015765585, 0.0...  [0.051144704, 0.9260171, 0.00950...  [0.051144704, 0.9260171, 0.00950...  [0.15384616, 0.23076923, 0.07692...  [0.42985076, 0.1522388, 0.089552...  [0.42985076, 0.1522388, 0.089552...
24  50   3       116   41    3  0.0        41  [0.0042242263, 0.0015765585, 0.0...  [0.051144704, 0.9260171, 0.00950...  [0.051144704, 0.9260171, 0.00950...  [0.15384616, 0.23076923, 0.07692...  [0.42985076, 0.1522388, 0.089552...  [0.42985076, 0.1522388, 0.089552...
25  50   4       116   41    3  0.0        41  [0.0042242263, 0.0015765585, 0.0...  [0.051144704, 0.9260171, 0.00950...  [0.051144704, 0.9260171, 0.00950...  [0.15384616, 0.23076923, 0.07692...  [0.42985076, 0.1522388, 0.089552...  [0.42985076, 0.1522388, 0.089552...
26  50   5       116   41    3  0.0        41  [0.0042242263, 0.0015765585, 0.0...  [0.051144704, 0.9260171, 0.00950...  [0.051144704, 0.9260171, 0.00950...  [0.15384616, 0.23076923, 0.07692...  [0.42985076, 0.1522388, 0.089552...  [0.42985076, 0.1522388, 0.089552...
27  50   6       116   41    3  0.0        17  [0.0042242263, 0.0015765585, 0.0...  [0.051144704, 0.9260171, 0.00950...  [0.00037134442, 0.026493562, 0.0...  [0.15384616, 0.23076923, 0.07692...  [0.42985076, 0.1522388, 0.089552...  [0.6468144, 0.1565097, 0.0484764...
28  50   7       116   17    2  0.0        41  [0.0042242263, 0.0015765585, 0.0...  [0.00037134442, 0.026493562, 0.0...  [0.051144704, 0.9260171, 0.00950...  [0.15384616, 0.23076923, 0.07692...  [0.6468144, 0.1565097, 0.0484764...  [0.42985076, 0.1522388, 0.089552...
29  50   8       116   41    1  0.0        41  [0.0042242263, 0.0015765585, 0.0...  [0.051144704, 0.9260171, 0.00950...  [0.051144704, 0.9260171, 0.00950...  [0.15384616, 0.23076923, 0.07692...  [0.42985076, 0.1522388, 0.089552...  [0.42985076, 0.1522388, 0.089552...
30  50   9       116   41    1  0.0        41  [0.0042242263, 0.0015765585, 0.0...  [0.051144704, 0.9260171, 0.00950...  [0.051144704, 0.9260171, 0.00950...  [0.15384616, 0.23076923, 0.07692...  [0.42985076, 0.1522388, 0.089552...  [0.42985076, 0.1522388, 0.089552...
31  50  10       116   41    1  0.0        41  [0.0042242263, 0.0015765585, 0.0...  [0.051144704, 0.9260171, 0.00950...  [0.051144704, 0.9260171, 0.00950...  [0.15384616, 0.23076923, 0.07692...  [0.42985076, 0.1522388, 0.089552...  [0.42985076, 0.1522388, 0.089552...
32  50  11       116   41    1  0.0         2  [0.0042242263, 0.0015765585, 0.0...  [0.051144704, 0.9260171, 0.00950...  [0.0014877882, 0.41098294, 0.481...  [0.15384616, 0.23076923, 0.07692...  [0.42985076, 0.1522388, 0.089552...  [0.34615386, 0.21794872, 0.21367...
33  50  12       116    2    1  0.0         2  [0.0042242263, 0.0015765585, 0.0...  [0.0014877882, 0.41098294, 0.481...  [0.0014877882, 0.41098294, 0.481...  [0.15384616, 0.23076923, 0.07692...  [0.34615386, 0.21794872, 0.21367...  [0.34615386, 0.21794872, 0.21367...
34  50  13       116    2    0  0.0       181  [0.0042242263, 0.0015765585, 0.0...  [0.0014877882, 0.41098294, 0.481...  [0.5756498, 0.02867316, 0.242340...  [0.15384616, 0.23076923, 0.07692...  [0.34615386, 0.21794872, 0.21367...  [0.8857143, 0.057142857, 0.03238...
35  50  14       116  181    0  0.0       181  [0.0042242263, 0.0015765585, 0.0...  [0.5756498, 0.02867316, 0.242340...  [0.5756498, 0.02867316, 0.242340...  [0.15384616, 0.23076923, 0.07692...  [0.8857143, 0.057142857, 0.03238...  [0.8857143, 0.057142857, 0.03238...
36  50  15       116  181    0  0.0       181  [0.0042242263, 0.0015765585, 0.0...  [0.5756498, 0.02867316, 0.242340...  [0.5756498, 0.02867316, 0.242340...  [0.15384616, 0.23076923, 0.07692...  [0.8857143, 0.057142857, 0.03238...  [0.8857143, 0.057142857, 0.03238...
37  50  16       116  181    0  0.0       181  [0.0042242263, 0.0015765585, 0.0...  [0.5756498, 0.02867316, 0.242340...  [0.5756498, 0.02867316, 0.242340...  [0.15384616, 0.23076923, 0.07692...  [0.8857143, 0.057142857, 0.03238...  [0.8857143, 0.057142857, 0.03238...
38  50  17       116  181    0  0.0       181  [0.0042242263, 0.0015765585, 0.0...  [0.5756498, 0.02867316, 0.242340...  [0.5756498, 0.02867316, 0.242340...  [0.15384616, 0.23076923, 0.07692...  [0.8857143, 0.057142857, 0.03238...  [0.8857143, 0.057142857, 0.03238...
39  50  18       116  181    0  0.0         2  [0.0042242263, 0.0015765585, 0.0...  [0.5756498, 0.02867316, 0.242340...  [0.0014877882, 0.41098294, 0.481...  [0.15384616, 0.23076923, 0.07692...  [0.8857143, 0.057142857, 0.03238...  [0.34615386, 0.21794872, 0.21367...
40  50  19       116    2    0  0.0         2  [0.0042242263, 0.0015765585, 0.0...  [0.0014877882, 0.41098294, 0.481...  [0.0014877882, 0.41098294, 0.481...  [0.15384616, 0.23076923, 0.07692...  [0.34615386, 0.21794872, 0.21367...  [0.34615386, 0.21794872, 0.21367...
41  50  20       116    2    0  0.0       181  [0.0042242263, 0.0015765585, 0.0...  [0.0014877882, 0.41098294, 0.481...  [0.5756498, 0.02867316, 0.242340...  [0.15384616, 0.23076923, 0.07692...  [0.34615386, 0.21794872, 0.21367...  [0.8857143, 0.057142857, 0.03238...
42  50  21       116  181    0  0.0         2  [0.0042242263, 0.0015765585, 0.0...  [0.5756498, 0.02867316, 0.242340...  [0.0014877882, 0.41098294, 0.481...  [0.15384616, 0.23076923, 0.07692...  [0.8857143, 0.057142857, 0.03238...  [0.34615386, 0.21794872, 0.21367...
43  50  22       116    2    0  0.0         2  [0.0042242263, 0.0015765585, 0.0...  [0.0014877882, 0.41098294, 0.481...  [0.0014877882, 0.41098294, 0.481...  [0.15384616, 0.23076923, 0.07692...  [0.34615386, 0.21794872, 0.21367...  [0.34615386, 0.21794872, 0.21367...
44  50  23       116    2    3  0.0         2  [0.0042242263, 0.0015765585, 0.0...  [0.0014877882, 0.41098294, 0.481...  [0.0014877882, 0.41098294, 0.481...  [0.15384616, 0.23076923, 0.07692...  [0.34615386, 0.21794872, 0.21367...  [0.34615386, 0.21794872, 0.21367...
45  50  24       116    2    3  0.0         2  [0.0042242263, 0.0015765585, 0.0...  [0.0014877882, 0.41098294, 0.481...  [0.0014877882, 0.41098294, 0.481...  [0.15384616, 0.23076923, 0.07692...  [0.34615386, 0.21794872, 0.21367...  [0.34615386, 0.21794872, 0.21367...
46  50  25       116    2    3  0.0        41  [0.0042242263, 0.0015765585, 0.0...  [0.0014877882, 0.41098294, 0.481...  [0.051144704, 0.9260171, 0.00950...  [0.15384616, 0.23076923, 0.07692...  [0.34615386, 0.21794872, 0.21367...  [0.42985076, 0.1522388, 0.089552...
47  50  26       116   41    3  0.0        17  [0.0042242263, 0.0015765585, 0.0...  [0.051144704, 0.9260171, 0.00950...  [0.00037134442, 0.026493562, 0.0...  [0.15384616, 0.23076923, 0.07692...  [0.42985076, 0.1522388, 0.089552...  [0.6468144, 0.1565097, 0.0484764...
48  50  27       116   17    2  0.0       181  [0.0042242263, 0.0015765585, 0.0...  [0.00037134442, 0.026493562, 0.0...  [0.5756498, 0.02867316, 0.242340...  [0.15384616, 0.23076923, 0.07692...  [0.6468144, 0.1565097, 0.0484764...  [0.8857143, 0.057142857, 0.03238...
49  50  28       116  181    1  0.0         2  [0.0042242263, 0.0015765585, 0.0...  [0.5756498, 0.02867316, 0.242340...  [0.0014877882, 0.41098294, 0.481...  [0.15384616, 0.23076923, 0.07692...  [0.8857143, 0.057142857, 0.03238...  [0.34615386, 0.21794872, 0.21367...

k='exploratory'

    id   t  obs_init  obs  act  rew  obs_next                           probs_init                                probs                           probs_next                  probs_init_behavior                       probs_behavior                  probs_next_behavior
0    0   0        97   97    1    0        42  [0.010809051, 0.24719085, 0.3298...  [0.010809051, 0.24719085, 0.3298...  [0.011781467, 0.74776983, 0.0380...  [0.16132273, 0.22178493, 0.27190...  [0.16132273, 0.22178493, 0.27190...  [0.20344493, 0.21813123, 0.09033...
1    0   1        97   42    3    0        58  [0.010809051, 0.24719085, 0.3298...  [0.011781467, 0.74776983, 0.0380...  [0.0011493295, 5.6734436e-05, 0....  [0.16132273, 0.22178493, 0.27190...  [0.20344493, 0.21813123, 0.09033...  [0.07012338, 0.08904895, 0.66289...
2    0   2        97   58    0    0       256  [0.010809051, 0.24719085, 0.3298...  [0.0011493295, 5.6734436e-05, 0....            [0.2, 0.2, 0.2, 0.2, 0.2]  [0.16132273, 0.22178493, 0.27190...  [0.07012338, 0.08904895, 0.66289...            [0.2, 0.2, 0.2, 0.2, 0.2]
3    0   3        97  256    1    0       256  [0.010809051, 0.24719085, 0.3298...            [0.2, 0.2, 0.2, 0.2, 0.2]            [0.2, 0.2, 0.2, 0.2, 0.2]  [0.16132273, 0.22178493, 0.27190...            [0.2, 0.2, 0.2, 0.2, 0.2]            [0.2, 0.2, 0.2, 0.2, 0.2]
4    1   0        42   42    1    0         7  [0.011781467, 0.74776983, 0.0380...  [0.011781467, 0.74776983, 0.0380...  [0.013137155, 0.0044722464, 0.06...  [0.20344493, 0.21813123, 0.09033...  [0.20344493, 0.21813123, 0.09033...  [0.15488867, 0.122650914, 0.0891...
5    1   1        42    7    4    0         7  [0.011781467, 0.74776983, 0.0380...  [0.013137155, 0.0044722464, 0.06...  [0.013137155, 0.0044722464, 0.06...  [0.20344493, 0.21813123, 0.09033...  [0.15488867, 0.122650914, 0.0891...  [0.15488867, 0.122650914, 0.0891...
6    1   2        42    7    0    0        97  [0.011781467, 0.74776983, 0.0380...  [0.013137155, 0.0044722464, 0.06...  [0.010809051, 0.24719085, 0.3298...  [0.20344493, 0.21813123, 0.09033...  [0.15488867, 0.122650914, 0.0891...  [0.16132273, 0.22178493, 0.27190...
7    1   3        42   97    2    0        42  [0.011781467, 0.74776983, 0.0380...  [0.010809051, 0.24719085, 0.3298...  [0.011781467, 0.74776983, 0.0380...  [0.20344493, 0.21813123, 0.09033...  [0.16132273, 0.22178493, 0.27190...  [0.20344493, 0.21813123, 0.09033...
8    1   4        42   42    2    0        42  [0.011781467, 0.74776983, 0.0380...  [0.011781467, 0.74776983, 0.0380...  [0.011781467, 0.74776983, 0.0380...  [0.20344493, 0.21813123, 0.09033...  [0.20344493, 0.21813123, 0.09033...  [0.20344493, 0.21813123, 0.09033...
9    1   5        42   42    1    0       100  [0.011781467, 0.74776983, 0.0380...  [0.011781467, 0.74776983, 0.0380...  [0.002528379, 0.12706457, 0.0037...  [0.20344493, 0.21813123, 0.09033...  [0.20344493, 0.21813123, 0.09033...  [0.15991202, 0.13607644, 0.22803...
10   1   6        42  100    2    0        25  [0.011781467, 0.74776983, 0.0380...  [0.002528379, 0.12706457, 0.0037...  [0.0017155914, 0.8569119, 0.1151...  [0.20344493, 0.21813123, 0.09033...  [0.15991202, 0.13607644, 0.22803...  [0.086945, 0.3057545, 0.2204868,...
11   1   7        42   25    2    0        98  [0.011781467, 0.74776983, 0.0380...  [0.0017155914, 0.8569119, 0.1151...  [0.014864901, 0.94889903, 0.0028...  [0.20344493, 0.21813123, 0.09033...  [0.086945, 0.3057545, 0.2204868,...  [0.23847172, 0.2637637, 0.187244...
12   1   8        42   98    1    0        42  [0.011781467, 0.74776983, 0.0380...  [0.014864901, 0.94889903, 0.0028...  [0.011781467, 0.74776983, 0.0380...  [0.20344493, 0.21813123, 0.09033...  [0.23847172, 0.2637637, 0.187244...  [0.20344493, 0.21813123, 0.09033...
13   1   9        42   42    0    0        42  [0.011781467, 0.74776983, 0.0380...  [0.011781467, 0.74776983, 0.0380...  [0.011781467, 0.74776983, 0.0380...  [0.20344493, 0.21813123, 0.09033...  [0.20344493, 0.21813123, 0.09033...  [0.20344493, 0.21813123, 0.09033...
14   1  10        42   42    4    0        15  [0.011781467, 0.74776983, 0.0380...  [0.011781467, 0.74776983, 0.0380...  [0.0011581172, 0.08655262, 0.0, ...  [0.20344493, 0.21813123, 0.09033...  [0.20344493, 0.21813123, 0.09033...  [0.14858232, 0.21410696, 0.0, 0....
15   1  11        42   15    3    0       189  [0.011781467, 0.74776983, 0.0380...  [0.0011581172, 0.08655262, 0.0, ...  [0.0058348905, 0.96134967, 0.030...  [0.20344493, 0.21813123, 0.09033...  [0.14858232, 0.21410696, 0.0, 0....  [0.13660094, 0.49081907, 0.28935...
16   1  12        42  189    0    0       254  [0.011781467, 0.74776983, 0.0380...  [0.0058348905, 0.96134967, 0.030...  [0.23725273, 0.742851, 0.0198962...  [0.20344493, 0.21813123, 0.09033...  [0.13660094, 0.49081907, 0.28935...  [0.11264128, 0.25259227, 0.63476...
17   1  13        42  254    2    0       254  [0.011781467, 0.74776983, 0.0380...  [0.23725273, 0.742851, 0.0198962...  [0.23725273, 0.742851, 0.0198962...  [0.20344493, 0.21813123, 0.09033...  [0.11264128, 0.25259227, 0.63476...  [0.11264128, 0.25259227, 0.63476...
18   1  14        42  254    1    0       208  [0.011781467, 0.74776983, 0.0380...  [0.23725273, 0.742851, 0.0198962...  [0.011361285, 0.4663457, 0.29059...  [0.20344493, 0.21813123, 0.09033...  [0.11264128, 0.25259227, 0.63476...  [0.12320061, 0.3191372, 0.179972...
19   1  15        42  208    2    0        12  [0.011781467, 0.74776983, 0.0380...  [0.011361285, 0.4663457, 0.29059...  [0.03244175, 0.16740343, 0.38088...  [0.20344493, 0.21813123, 0.09033...  [0.12320061, 0.3191372, 0.179972...  [0.2248789, 0.12636597, 0.374730...
20   1  16        42   12    3    0        12  [0.011781467, 0.74776983, 0.0380...  [0.03244175, 0.16740343, 0.38088...  [0.03244175, 0.16740343, 0.38088...  [0.20344493, 0.21813123, 0.09033...  [0.2248789, 0.12636597, 0.374730...  [0.2248789, 0.12636597, 0.374730...
21   1  17        42   12    0    0        12  [0.011781467, 0.74776983, 0.0380...  [0.03244175, 0.16740343, 0.38088...  [0.03244175, 0.16740343, 0.38088...  [0.20344493, 0.21813123, 0.09033...  [0.2248789, 0.12636597, 0.374730...  [0.2248789, 0.12636597, 0.374730...
22   1  18        42   12    2    0        12  [0.011781467, 0.74776983, 0.0380...  [0.03244175, 0.16740343, 0.38088...  [0.03244175, 0.16740343, 0.38088...  [0.20344493, 0.21813123, 0.09033...  [0.2248789, 0.12636597, 0.374730...  [0.2248789, 0.12636597, 0.374730...
23   1  19        42   12    2    0        12  [0.011781467, 0.74776983, 0.0380...  [0.03244175, 0.16740343, 0.38088...  [0.03244175, 0.16740343, 0.38088...  [0.20344493, 0.21813123, 0.09033...  [0.2248789, 0.12636597, 0.374730...  [0.2248789, 0.12636597, 0.374730...
24   1  20        42   12    2    0        12  [0.011781467, 0.74776983, 0.0380...  [0.03244175, 0.16740343, 0.38088...  [0.03244175, 0.16740343, 0.38088...  [0.20344493, 0.21813123, 0.09033...  [0.2248789, 0.12636597, 0.374730...  [0.2248789, 0.12636597, 0.374730...
25   1  21        42   12    2    0        12  [0.011781467, 0.74776983, 0.0380...  [0.03244175, 0.16740343, 0.38088...  [0.03244175, 0.16740343, 0.38088...  [0.20344493, 0.21813123, 0.09033...  [0.2248789, 0.12636597, 0.374730...  [0.2248789, 0.12636597, 0.374730...
26   1  22        42   12    4    1       257  [0.011781467, 0.74776983, 0.0380...  [0.03244175, 0.16740343, 0.38088...            [0.2, 0.2, 0.2, 0.2, 0.2]  [0.20344493, 0.21813123, 0.09033...  [0.2248789, 0.12636597, 0.374730...            [0.2, 0.2, 0.2, 0.2, 0.2]
27   1  23        42  257    4    0       257  [0.011781467, 0.74776983, 0.0380...            [0.2, 0.2, 0.2, 0.2, 0.2]            [0.2, 0.2, 0.2, 0.2, 0.2]  [0.20344493, 0.21813123, 0.09033...            [0.2, 0.2, 0.2, 0.2, 0.2]            [0.2, 0.2, 0.2, 0.2, 0.2]
28   2   0       144  144    4    0       247  [0.0010556276, 0.8245456, 0.1627...  [0.0010556276, 0.8245456, 0.1627...  [0.07086289, 0.5789317, 0.121557...  [0.24928819, 0.23072232, 0.21872...  [0.24928819, 0.23072232, 0.21872...  [0.08967947, 0.13460407, 0.30532...
29   2   1       144  247    4    0       144  [0.0010556276, 0.8245456, 0.1627...  [0.07086289, 0.5789317, 0.121557...  [0.0010556276, 0.8245456, 0.1627...  [0.24928819, 0.23072232, 0.21872...  [0.08967947, 0.13460407, 0.30532...  [0.24928819, 0.23072232, 0.21872...
30   2   2       144  144    0    0       144  [0.0010556276, 0.8245456, 0.1627...  [0.0010556276, 0.8245456, 0.1627...  [0.0010556276, 0.8245456, 0.1627...  [0.24928819, 0.23072232, 0.21872...  [0.24928819, 0.23072232, 0.21872...  [0.24928819, 0.23072232, 0.21872...
31   2   3       144  144    1    0       144  [0.0010556276, 0.8245456, 0.1627...  [0.0010556276, 0.8245456, 0.1627...  [0.0010556276, 0.8245456, 0.1627...  [0.24928819, 0.23072232, 0.21872...  [0.24928819, 0.23072232, 0.21872...  [0.24928819, 0.23072232, 0.21872...
32   2   4       144  144    0    0       179  [0.0010556276, 0.8245456, 0.1627...  [0.0010556276, 0.8245456, 0.1627...  [0.18146195, 0.025168937, 0.0182...  [0.24928819, 0.23072232, 0.21872...  [0.24928819, 0.23072232, 0.21872...  [0.061037466, 0.3209795, 0.12857...
33   2   5       144  179    4    0       144  [0.0010556276, 0.8245456, 0.1627...  [0.18146195, 0.025168937, 0.0182...  [0.0010556276, 0.8245456, 0.1627...  [0.24928819, 0.23072232, 0.21872...  [0.061037466, 0.3209795, 0.12857...  [0.24928819, 0.23072232, 0.21872...
34   2   6       144  144    0    0       175  [0.0010556276, 0.8245456, 0.1627...  [0.0010556276, 0.8245456, 0.1627...  [0.015388386, 0.0020073925, 0.00...  [0.24928819, 0.23072232, 0.21872...  [0.24928819, 0.23072232, 0.21872...  [0.26211366, 0.31838974, 0.13508...
35   2   7       144  175    4    0       175  [0.0010556276, 0.8245456, 0.1627...  [0.015388386, 0.0020073925, 0.00...  [0.015388386, 0.0020073925, 0.00...  [0.24928819, 0.23072232, 0.21872...  [0.26211366, 0.31838974, 0.13508...  [0.26211366, 0.31838974, 0.13508...
36   2   8       144  175    4    0       175  [0.0010556276, 0.8245456, 0.1627...  [0.015388386, 0.0020073925, 0.00...  [0.015388386, 0.0020073925, 0.00...  [0.24928819, 0.23072232, 0.21872...  [0.26211366, 0.31838974, 0.13508...  [0.26211366, 0.31838974, 0.13508...
37   2   9       144  175    1    0       247  [0.0010556276, 0.8245456, 0.1627...  [0.015388386, 0.0020073925, 0.00...  [0.07086289, 0.5789317, 0.121557...  [0.24928819, 0.23072232, 0.21872...  [0.26211366, 0.31838974, 0.13508...  [0.08967947, 0.13460407, 0.30532...
38   2  10       144  247    4    0       247  [0.0010556276, 0.8245456, 0.1627...  [0.07086289, 0.5789317, 0.121557...  [0.07086289, 0.5789317, 0.121557...  [0.24928819, 0.23072232, 0.21872...  [0.08967947, 0.13460407, 0.30532...  [0.08967947, 0.13460407, 0.30532...
39   2  11       144  247    2    0       247  [0.0010556276, 0.8245456, 0.1627...  [0.07086289, 0.5789317, 0.121557...  [0.07086289, 0.5789317, 0.121557...  [0.24928819, 0.23072232, 0.21872...  [0.08967947, 0.13460407, 0.30532...  [0.08967947, 0.13460407, 0.30532...
40   2  12       144  247    2    1       257  [0.0010556276, 0.8245456, 0.1627...  [0.07086289, 0.5789317, 0.121557...            [0.2, 0.2, 0.2, 0.2, 0.2]  [0.24928819, 0.23072232, 0.21872...  [0.08967947, 0.13460407, 0.30532...            [0.2, 0.2, 0.2, 0.2, 0.2]
41   2  13       144  257    4    0       257  [0.0010556276, 0.8245456, 0.1627...            [0.2, 0.2, 0.2, 0.2, 0.2]            [0.2, 0.2, 0.2, 0.2, 0.2]  [0.24928819, 0.23072232, 0.21872...            [0.2, 0.2, 0.2, 0.2, 0.2]            [0.2, 0.2, 0.2, 0.2, 0.2]
42   3   0        17   17    2    0         2  [0.00037134442, 0.026493562, 0.0...  [0.00037134442, 0.026493562, 0.0...  [0.0014877882, 0.41098294, 0.481...  [0.15655875, 0.15166737, 0.33282...  [0.15655875, 0.15166737, 0.33282...  [0.114609644, 0.17534328, 0.1660...
43   3   1        17    2    2    0         2  [0.00037134442, 0.026493562, 0.0...  [0.0014877882, 0.41098294, 0.481...  [0.0014877882, 0.41098294, 0.481...  [0.15655875, 0.15166737, 0.33282...  [0.114609644, 0.17534328, 0.1660...  [0.114609644, 0.17534328, 0.1660...
44   3   2        17    2    4    0         2  [0.00037134442, 0.026493562, 0.0...  [0.0014877882, 0.41098294, 0.481...  [0.0014877882, 0.41098294, 0.481...  [0.15655875, 0.15166737, 0.33282...  [0.114609644, 0.17534328, 0.1660...  [0.114609644, 0.17534328, 0.1660...
45   3   3        17    2    1    0         2  [0.00037134442, 0.026493562, 0.0...  [0.0014877882, 0.41098294, 0.481...  [0.0014877882, 0.41098294, 0.481...  [0.15655875, 0.15166737, 0.33282...  [0.114609644, 0.17534328, 0.1660...  [0.114609644, 0.17534328, 0.1660...
46   3   4        17    2    4    0         2  [0.00037134442, 0.026493562, 0.0...  [0.0014877882, 0.41098294, 0.481...  [0.0014877882, 0.41098294, 0.481...  [0.15655875, 0.15166737, 0.33282...  [0.114609644, 0.17534328, 0.1660...  [0.114609644, 0.17534328, 0.1660...
47   3   5        17    2    3    0         2  [0.00037134442, 0.026493562, 0.0...  [0.0014877882, 0.41098294, 0.481...  [0.0014877882, 0.41098294, 0.481...  [0.15655875, 0.15166737, 0.33282...  [0.114609644, 0.17534328, 0.1660...  [0.114609644, 0.17534328, 0.1660...
48   3   6        17    2    2    0         2  [0.00037134442, 0.026493562, 0.0...  [0.0014877882, 0.41098294, 0.481...  [0.0014877882, 0.41098294, 0.481...  [0.15655875, 0.15166737, 0.33282...  [0.114609644, 0.17534328, 0.1660...  [0.114609644, 0.17534328, 0.1660...
49   3   7        17    2    1    0       181  [0.00037134442, 0.026493562, 0.0...  [0.0014877882, 0.41098294, 0.481...  [0.5756498, 0.02867316, 0.242340...  [0.15655875, 0.15166737, 0.33282...  [0.114609644, 0.17534328, 0.1660...  [0.17352399, 0.25527307, 0.17809...

k='evaluation'

    id   t  obs_init  obs  act  rew  obs_next                           probs_init                                probs                           probs_next
0    0   0        97   97    3    0       160  [0.010809051, 0.24719085, 0.3298...  [0.010809051, 0.24719085, 0.3298...  [0.0015649342, 0.0039521875, 0.5...
1    0   1        97  160    4    0       244  [0.010809051, 0.24719085, 0.3298...  [0.0015649342, 0.0039521875, 0.5...  [0.00048858585, 0.115405515, 0.8...
2    0   2        97  244    2    0       244  [0.010809051, 0.24719085, 0.3298...  [0.00048858585, 0.115405515, 0.8...  [0.00048858585, 0.115405515, 0.8...
3    0   3        97  244    1    0        48  [0.010809051, 0.24719085, 0.3298...  [0.00048858585, 0.115405515, 0.8...  [0.038448803, 0.18999942, 0.2633...
4    0   4        97   48    4    0       122  [0.010809051, 0.24719085, 0.3298...  [0.038448803, 0.18999942, 0.2633...  [0.0018696949, 0.98924035, 0.006...
5    0   5        97  122    1    0       244  [0.010809051, 0.24719085, 0.3298...  [0.0018696949, 0.98924035, 0.006...  [0.00048858585, 0.115405515, 0.8...
6    0   6        97  244    2    0       190  [0.010809051, 0.24719085, 0.3298...  [0.00048858585, 0.115405515, 0.8...  [0.007003612, 0.947661, 0.010028...
7    0   7        97  190    1    0       190  [0.010809051, 0.24719085, 0.3298...  [0.007003612, 0.947661, 0.010028...  [0.007003612, 0.947661, 0.010028...
8    0   8        97  190    1    0       190  [0.010809051, 0.24719085, 0.3298...  [0.007003612, 0.947661, 0.010028...  [0.007003612, 0.947661, 0.010028...
9    0   9        97  190    1    0       244  [0.010809051, 0.24719085, 0.3298...  [0.007003612, 0.947661, 0.010028...  [0.00048858585, 0.115405515, 0.8...
10   0  10        97  244    2    0       160  [0.010809051, 0.24719085, 0.3298...  [0.00048858585, 0.115405515, 0.8...  [0.0015649342, 0.0039521875, 0.5...
11   0  11        97  160    4    0       244  [0.010809051, 0.24719085, 0.3298...  [0.0015649342, 0.0039521875, 0.5...  [0.00048858585, 0.115405515, 0.8...
12   0  12        97  244    2    0        48  [0.010809051, 0.24719085, 0.3298...  [0.00048858585, 0.115405515, 0.8...  [0.038448803, 0.18999942, 0.2633...
13   0  13        97   48    4    0       122  [0.010809051, 0.24719085, 0.3298...  [0.038448803, 0.18999942, 0.2633...  [0.0018696949, 0.98924035, 0.006...
14   0  14        97  122    1    0       244  [0.010809051, 0.24719085, 0.3298...  [0.0018696949, 0.98924035, 0.006...  [0.00048858585, 0.115405515, 0.8...
15   0  15        97  244    2    0        48  [0.010809051, 0.24719085, 0.3298...  [0.00048858585, 0.115405515, 0.8...  [0.038448803, 0.18999942, 0.2633...
16   0  16        97   48    3    0       244  [0.010809051, 0.24719085, 0.3298...  [0.038448803, 0.18999942, 0.2633...  [0.00048858585, 0.115405515, 0.8...
17   0  17        97  244    3    0       244  [0.010809051, 0.24719085, 0.3298...  [0.00048858585, 0.115405515, 0.8...  [0.00048858585, 0.115405515, 0.8...
18   0  18        97  244    2    0        48  [0.010809051, 0.24719085, 0.3298...  [0.00048858585, 0.115405515, 0.8...  [0.038448803, 0.18999942, 0.2633...
19   0  19        97   48    3    0       244  [0.010809051, 0.24719085, 0.3298...  [0.038448803, 0.18999942, 0.2633...  [0.00048858585, 0.115405515, 0.8...
20   0  20        97  244    2    0        48  [0.010809051, 0.24719085, 0.3298...  [0.00048858585, 0.115405515, 0.8...  [0.038448803, 0.18999942, 0.2633...
21   0  21        97   48    2    0        48  [0.010809051, 0.24719085, 0.3298...  [0.038448803, 0.18999942, 0.2633...  [0.038448803, 0.18999942, 0.2633...
22   0  22        97   48    3    0        48  [0.010809051, 0.24719085, 0.3298...  [0.038448803, 0.18999942, 0.2633...  [0.038448803, 0.18999942, 0.2633...
23   0  23        97   48    2    0        48  [0.010809051, 0.24719085, 0.3298...  [0.038448803, 0.18999942, 0.2633...  [0.038448803, 0.18999942, 0.2633...
24   0  24        97   48    1    0        19  [0.010809051, 0.24719085, 0.3298...  [0.038448803, 0.18999942, 0.2633...  [0.060240082, 0.0002806649, 0.00...
25   0  25        97   19    4    0        19  [0.010809051, 0.24719085, 0.3298...  [0.060240082, 0.0002806649, 0.00...  [0.060240082, 0.0002806649, 0.00...
26   0  26        97   19    4    0        19  [0.010809051, 0.24719085, 0.3298...  [0.060240082, 0.0002806649, 0.00...  [0.060240082, 0.0002806649, 0.00...
27   0  27        97   19    4    0        19  [0.010809051, 0.24719085, 0.3298...  [0.060240082, 0.0002806649, 0.00...  [0.060240082, 0.0002806649, 0.00...
28   0  28        97   19    4    0        19  [0.010809051, 0.24719085, 0.3298...  [0.060240082, 0.0002806649, 0.00...  [0.060240082, 0.0002806649, 0.00...
29   0  29        97   19    4    0        19  [0.010809051, 0.24719085, 0.3298...  [0.060240082, 0.0002806649, 0.00...  [0.060240082, 0.0002806649, 0.00...
30   0  30        97   19    4    0        19  [0.010809051, 0.24719085, 0.3298...  [0.060240082, 0.0002806649, 0.00...  [0.060240082, 0.0002806649, 0.00...
31   0  31        97   19    4    0        19  [0.010809051, 0.24719085, 0.3298...  [0.060240082, 0.0002806649, 0.00...  [0.060240082, 0.0002806649, 0.00...
32   0  32        97   19    4    0        19  [0.010809051, 0.24719085, 0.3298...  [0.060240082, 0.0002806649, 0.00...  [0.060240082, 0.0002806649, 0.00...
33   0  33        97   19    4    0       256  [0.010809051, 0.24719085, 0.3298...  [0.060240082, 0.0002806649, 0.00...            [0.2, 0.2, 0.2, 0.2, 0.2]
34   0  34        97  256    3    0       256  [0.010809051, 0.24719085, 0.3298...            [0.2, 0.2, 0.2, 0.2, 0.2]            [0.2, 0.2, 0.2, 0.2, 0.2]
35   1   0       183  183    3    0       183  [0.0009828103, 0.0017260762, 0.0...  [0.0009828103, 0.0017260762, 0.0...  [0.0009828103, 0.0017260762, 0.0...
36   1   1       183  183    3    0       159  [0.0009828103, 0.0017260762, 0.0...  [0.0009828103, 0.0017260762, 0.0...  [0.019768849, 0.012857678, 0.001...
37   1   2       183  159    3    0       159  [0.0009828103, 0.0017260762, 0.0...  [0.019768849, 0.012857678, 0.001...  [0.019768849, 0.012857678, 0.001...
38   1   3       183  159    3    0       179  [0.0009828103, 0.0017260762, 0.0...  [0.019768849, 0.012857678, 0.001...  [0.18146195, 0.025168937, 0.0182...
39   1   4       183  179    4    0       179  [0.0009828103, 0.0017260762, 0.0...  [0.18146195, 0.025168937, 0.0182...  [0.18146195, 0.025168937, 0.0182...
40   1   5       183  179    4    0       179  [0.0009828103, 0.0017260762, 0.0...  [0.18146195, 0.025168937, 0.0182...  [0.18146195, 0.025168937, 0.0182...
41   1   6       183  179    2    0       179  [0.0009828103, 0.0017260762, 0.0...  [0.18146195, 0.025168937, 0.0182...  [0.18146195, 0.025168937, 0.0182...
42   1   7       183  179    4    0       195  [0.0009828103, 0.0017260762, 0.0...  [0.18146195, 0.025168937, 0.0182...  [0.02480495, 0.7613253, 0.104794...
43   1   8       183  195    1    0       195  [0.0009828103, 0.0017260762, 0.0...  [0.02480495, 0.7613253, 0.104794...  [0.02480495, 0.7613253, 0.104794...
44   1   9       183  195    1    0        40  [0.0009828103, 0.0017260762, 0.0...  [0.02480495, 0.7613253, 0.104794...  [0.047417417, 0.002985682, 0.028...
45   1  10       183   40    4    0        40  [0.0009828103, 0.0017260762, 0.0...  [0.047417417, 0.002985682, 0.028...  [0.047417417, 0.002985682, 0.028...
46   1  11       183   40    4    0        40  [0.0009828103, 0.0017260762, 0.0...  [0.047417417, 0.002985682, 0.028...  [0.047417417, 0.002985682, 0.028...
47   1  12       183   40    4    0        40  [0.0009828103, 0.0017260762, 0.0...  [0.047417417, 0.002985682, 0.028...  [0.047417417, 0.002985682, 0.028...
48   1  13       183   40    4    0        40  [0.0009828103, 0.0017260762, 0.0...  [0.047417417, 0.002985682, 0.028...  [0.047417417, 0.002985682, 0.028...
49   1  14       183   40    3    0       179  [0.0009828103, 0.0017260762, 0.0...  [0.047417417, 0.002985682, 0.028...  [0.18146195, 0.025168937, 0.0182...