In [1]:
%load_ext autoreload
%autoreload 2

# `import`

In [ ]:
import os
import warnings

import numpy as np
import pandas as pd
import tensorflow as tf

from collections import defaultdict

from medical_rl.libs.RL import Model
from medical_rl.libs.envs import get_env
from medical_rl.libs.cluster import get_data_clustered
from medical_rl.data_formatters.amsterdam import AmsterdamFormatter

from dice_rl_TU_Vienna.wrappers import AbsorbingWrapper, LoopingWrapper
from dice_rl_TU_Vienna.dataset import get_dataset_from_df, get_dataset_from_env
from dice_rl_TU_Vienna.estimators.onpolicy import OnPE
from dice_rl_TU_Vienna.utils.pandas import head_by_id
from dice_rl_TU_Vienna.plugins.stable_baselines3.policy import (
    get_model_MaskablePPO, get_probs_MaskablePPO, )

from plugins.sepsis.bologheanu.config import *

/Users/richardweiss/Documents/.venvs/dice_rl_TU_Vienna/lib/python3.11/site-packages/torch/utils/_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(

In [3]:
pd.set_option("display.max_rows", 100)

# Prepare

In [4]:
# constants continuous

seed = 42
n_act = 5

In [5]:
# constants tabular

# ---------------------------------------------------------------- #

# policies

total_timesteps = {
    "exploratory": 10_000,
    "evaluation": 100_000,
}

# ---------------------------------------------------------------- #
# clustering

seed = 42
n_clusters = 256
n_init = 10

n_obs = n_clusters + 2
n_act = 5

# ---------------------------------------------------------------- #
# dataset

n_trajectories = 10_000
max_trajectory_length = None
# seed

# ---------------------------------------------------------------- #

In [6]:
def RL_split_to_dataset_primal(RL_split, tabular):

    dtype_obs = np.int64 if tabular else np.float32

    split_id, split_t, split_obs, split_act, split_ret = RL_split

    split_id  = np.array(split_id,  dtype=np.int64)
    split_t   = np.array(split_t,   dtype=np.int64)
    split_obs = np.array(split_obs, dtype=dtype_obs)
    split_act = np.array(split_act, dtype=np.int64)
    split_ret = np.array(split_ret, dtype=np.float32)

    id  = []
    t   = []
    obs = []
    act = []
    rew = []

    obs_init = []
    obs_next = []

    i_init = 0; i_next = None
    for i in range( len(split_id) ):

        # first trajectory position
        A = i > 0 and split_id[i] != split_id[i-1]

        # last trajectory position
        B = i == len(split_id) - 1 or split_id[i+1] != split_id[i]

        if A:
            i_init = i

        if B:
            continue
        else:
            i_next = i+1

        # second last trajectory position
        C = i == len(split_id) - 2 or split_id[i+2] != split_id[i]

        id .append(split_id [i])
        t  .append(split_t  [i])
        obs.append(split_obs[i])
        act.append(split_act[i])
        rew.append(split_ret[i] if C else 0)

        obs_init.append( split_obs[i_init] )
        obs_next.append( split_obs[i_next] )

    return pd.DataFrame({
        "id": id, "t": t,
        "obs_init": obs_init,
        "obs": obs, "act": act, "rew": rew,
        "obs_next": obs_next,
    })

In [7]:
def get_processing(processors=None):
    if processors is None: processors = []

    def processing(df):
        df = df.copy(deep=False)
        for processor in processors:
            df = processor(df)
        return df

    return processing

In [8]:
def add_terminal_transition(df):
    df = df.copy(deep=False)

    df_parts = []

    for id in df["id"].unique():
        df_part = df[ df["id"] == id ].reset_index(drop=True)

        row = df_part.loc[len(df_part)-1].copy()
        row["t"] += 1
        row["act"] = np.random.choice( range(n_act), p=row["probs_next"], )
        row["rew"] = 0
        for s in ["obs", "probs", "probs_behavior"]:
            if (s_next := f"{s}_next") in df_part.columns:
                row[s] = row[s_next]
        df_part.loc[len(df_part)] = row

        df_parts.append(df_part)

    df = pd.concat(df_parts).reset_index(drop=True)

    return df

In [ ]:
def assertion_terminal(dataset, i):
    assertion = True
    for s in ["obs", "probs", "probs_benavior"]:
        if s not in dataset.columns: continue

        x = dataset.loc[i,   "probs"]
        y = dataset.loc[i-1, "probs_next"]
        z = dataset.loc[i,   "probs_next"]

        if not np.all(x == y) and np.all(y == z):
            assertion = False

    return assertion

In [10]:
get_OnPV = lambda dataset: OnPE(dataset).solve(gamma=0.9)[0]

In [11]:
test = {}
bounds = {}
model = {}
dataset = {}

In [12]:
def load_datasets_raw():
    train, valid, test =  AmsterdamFormatter() \
        .load_random_split(dir_split)

    datasets_raw = {
        "train": train,
        "valid": valid,
        "test": test,
    }

    return datasets_raw

In [13]:
head_by_id(
    load_datasets_raw()["test"],
    n=2,
    id_name="ID",
)

,ID,Length of Stay,ACTH max,ACTH mean,ACTH min,ACTH std,AF Monitor max,AF Monitor mean,AF Monitor min,AF Monitor std,...,Fluid balance,AdmissionCount,Steroids,SOFA score,Age,Gender,Antibiotics,Antiviral,Antifungal,ICU Mortality
0,20.0,0,-0.080002,-0.088658,-0.088606,-0.025408,-0.094499,-0.078563,-0.081722,-0.164105,...,0.242128,-0.271663,1,-0.769852,3,1,1,0,0,0
1,20.0,1,-0.080002,-0.088658,-0.088606,-0.025408,-0.094499,-0.078563,-0.081722,-0.164105,...,-0.660426,-0.271663,1,-0.050286,3,1,1,0,0,0
2,20.0,2,-0.080002,-0.088658,-0.088606,-0.025408,-0.094499,-0.078563,-0.081722,-0.164105,...,-0.669512,-0.271663,1,-0.290141,3,1,1,0,0,0
3,20.0,3,-0.080002,-0.088658,-0.088606,-0.025408,-0.094499,-0.078563,-0.081722,-0.164105,...,-0.210015,-0.271663,1,-0.529997,3,1,1,0,0,0
4,20.0,4,-0.080002,-0.088658,-0.088606,-0.025408,-0.094499,-0.078563,-0.081722,-0.164105,...,-0.656099,-0.271663,1,-0.529997,3,1,1,0,0,0
5,20.0,5,-0.080002,-0.088658,-0.088606,-0.025408,-0.094499,-0.078563,-0.081722,-0.164105,...,-0.960701,-0.271663,1,-1.489417,3,1,1,0,0,0
6,20.0,6,-0.080002,-0.088658,-0.088606,-0.025408,-0.094499,-0.078563,-0.081722,-0.164105,...,-0.540143,-0.271663,1,-1.489417,3,1,1,0,0,0
7,20.0,7,-0.080002,-0.088658,-0.088606,-0.025408,-0.094499,-0.078563,-0.081722,-0.164105,...,0.154728,-0.271663,0,-0.529997,3,1,4,0,0,0
8,25.0,0,-0.080002,-0.088658,-0.088606,-0.025408,-0.238616,-0.310907,-0.819176,-0.542989,...,-0.154200,-0.271663,2,1.388845,4,2,0,0,0,1
9,25.0,1,-0.080002,-0.088658,-0.088606,-0.025408,0.121676,-0.039660,-1.451279,-0.724618,...,0.045695,-0.271663,2,1.388845,4,2,0,0,0,1
10,25.0,2,-0.080002,-0.088658,-0.088606,-0.025408,0.121676,-0.039660,-1.451279,-0.724618,...,1.157229,-0.271663,2,1.388845,4,2,1,0,0,1

# Tabular

## Dataset

In [29]:
hyperparameters={
    "seed": seed,
    "features": [
        'RRmean (ABP) mean',
        'RRmean (NIBP) mean',
        'Leukozyten max',
        'Heartrate mean',
        'Heartrate std',
        'Glucose mean',
        'Respiratory Rate resp min',
        'Noradrenaline (Norepinefrine) max',
        'Thrombozyten max',
        'PTT max',
        'PEEP max',
        'Fluid balance',
        'SOFA score',
        'Age',
        'Gender',
        'Antibiotics',
    ],
    "n_clusters": n_clusters,
    "n_init": n_init,
}

In [30]:
def dataset_raw_to_dataset_clustered_raw(
        dataset_raw, hyperparameters):

    dataset_clustered_raw = get_data_clustered(
        data=dataset_raw,
        features=hyperparameters["features"],
        n_clusters=hyperparameters["n_clusters"],
        n_init=hyperparameters["n_init"],
        seed=hyperparameters["seed"],
        path=dir_clustering,
    )

    return dataset_clustered_raw

In [31]:
head_by_id(
    dataset_raw_to_dataset_clustered_raw(
        load_datasets_raw()["test"],
        hyperparameters,
    ),
    n=2,
)

Trying to load data/medical_rl/sepsis_bologheanu/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/kmeans_model.pkl

    id  t  obs  act  ret
0   20  0   58    1    0
1   20  1  179    1    0
2   20  2   17    1    0
3   20  3   17    1    0
4   20  4   17    1    0
5   20  5   17    1    0
6   20  6   17    1    0
7   20  7  256    0    0
8   25  0  254    2    1
9   25  1  254    2    1
10  25  2  257    2    1

In [32]:
def dataset_clustered_raw_to_RL_split(df):
    return df["id"], df["t"], df["obs"], df["act"], df["ret"]

In [33]:
def dataset_clustered_raw_to_dataset_clustered_primal(dataset_clustered_raw):
    RL_split = dataset_clustered_raw_to_RL_split(dataset_clustered_raw)
    dataset_clustered_primal = RL_split_to_dataset_primal(RL_split, tabular=True)

    return dataset_clustered_primal

In [34]:
head_by_id(
    dataset_clustered_raw_to_dataset_clustered_primal(
        dataset_raw_to_dataset_clustered_raw(
            load_datasets_raw()["test"],
            hyperparameters,
        ),
    ),
    n=2,
)

Trying to load data/medical_rl/sepsis_bologheanu/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/kmeans_model.pkl

   id  t  obs_init  obs  act  rew  obs_next
0  20  0        58   58    1  0.0       179
1  20  1        58  179    1  0.0        17
2  20  2        58   17    1  0.0        17
3  20  3        58   17    1  0.0        17
4  20  4        58   17    1  0.0        17
5  20  5        58   17    1  0.0        17
6  20  6        58   17    1  0.0       256
7  25  0       254  254    2  0.0       254
8  25  1       254  254    2  1.0       257

In [35]:
def get_datasets_tabular_until_primal():
    datasets_raw = load_datasets_raw()
    datasets_clustered_raw = {
        k: dataset_raw_to_dataset_clustered_raw(v, hyperparameters)
            for k, v in datasets_raw.items()
    }
    datasets_clustered_primal = {
        k: dataset_clustered_raw_to_dataset_clustered_primal(v)
            for k, v in datasets_clustered_raw.items()
    }

    datasets_tabular = {
        "raw": datasets_raw,
        "clustered_raw": datasets_clustered_raw,
        "clustered_primal": datasets_clustered_primal
    }

    return datasets_tabular

In [36]:
dataset["tabular"] = get_datasets_tabular_until_primal()

Trying to load data/medical_rl/sepsis_bologheanu/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/kmeans_model.pkl
Trying to load data/medical_rl/sepsis_bologheanu/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/kmeans_model.pkl
Trying to load data/medical_rl/sepsis_bologheanu/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/kmeans_model.pkl

In [37]:
for label in labels:
    dataset["tabular"]["clustered_primal"][label].to_parquet(
        os.path.join(dir_clustering, f"{label}.parquet"), )

In [38]:
env = { label: {} for label in labels }
action_mask = {}

for label in labels:
    x, y = get_env(
        n_clusters=n_clusters,
        data_clustered=dataset["tabular"]["clustered_primal"][label],
    )

    env[label] = {
        "": x,
        "absorbing": AbsorbingWrapper(x),
        "looping": LoopingWrapper(x),
    }
    action_mask[label] = y

In [ ]:
model["tabular"] = {}
id_policy["tabular"] = {} # type: ignore

for name in names:
    if name == "original": continue

    x, y = get_model_MaskablePPO(
        dir_data=dir_clustering,
        env=env["train"][""],
        hyperparameters={
            "seed": seed,
            "total_timesteps": total_timesteps[name],
        },
    )

    model["tabular"][name] = x
    id_policy["tabular"][name] = y

def get_act_(name, obs):
    with warnings.catch_warnings(action="ignore", category=UserWarning):
        act, _ = model["tabular"][name].predict(obs, action_masks=action_mask["test"][obs])
        act = int(act)
        return act

get_act_exploratory = lambda obs: get_act_("exploratory", obs)
get_act_evaluation  = lambda obs: get_act_("evaluation",  obs)

get_act = {
    "exploratory": get_act_exploratory,
    "evaluation": get_act_evaluation,
}

dir_policy["tabular"] = {
    name: os_path_join(dir_clustering, id_policy["tabular"][name])
        for name in names
            if name != "original"
}

In [40]:
# final processing

def get_probs_behavior_dict(df):

    mults = defaultdict(lambda: [ 0 for act in range(n_act) ] )

    for i in range( len(df) ):
        obs = df.loc[i, "obs"]
        act = df.loc[i, "act"]
        mults[obs][act] += 1 # type: ignore

    probs = {
        k: np.array( v / np.sum(v), dtype=np.float32, )
        for k, v in mults.items()
    }

    return probs

def add_probs_tabular_evaluation(df):
    df = df.copy(deep=False)
    df["probs_init"] = list( get_probs_MaskablePPO(df["obs_init"], model["tabular"]["evaluation"], action_mask["test"]) )
    df["probs"]      = list( get_probs_MaskablePPO(df["obs"],      model["tabular"]["evaluation"], action_mask["test"]) )
    df["probs_next"] = list( get_probs_MaskablePPO(df["obs_next"], model["tabular"]["evaluation"], action_mask["test"]) )
    return df

def add_probs_tabular_behavior_original(df):
    df = df.copy(deep=False)
    probs_behavior_dict = get_probs_behavior_dict(df)
    df["probs_behavior_init"] = df["obs_init"].map(probs_behavior_dict)
    df["probs_behavior"]      = df["obs"]     .map(probs_behavior_dict)
    df["probs_behavior_next"] = df["obs_next"].map(probs_behavior_dict)
    uniform = np.ones(n_act, dtype=np.float32) / n_act
    df = df.map(lambda x: x if isinstance(x, np.ndarray) or not pd.isna(x) else uniform)
    return df

def add_probs_tabular_behavior_exploratory(df):
    df = df.copy(deep=False)
    df["probs_behavior_init"] = list( get_probs_MaskablePPO(df["obs_init"], model["tabular"]["exploratory"], action_mask["test"]) )
    df["probs_behavior"]      = list( get_probs_MaskablePPO(df["obs"],      model["tabular"]["exploratory"], action_mask["test"]) )
    df["probs_behavior_next"] = list( get_probs_MaskablePPO(df["obs_next"], model["tabular"]["exploratory"], action_mask["test"]) )
    return df

def cast_probs(df):
    df = df.copy(deep=False)
    cast_array = lambda x: np.array(x, dtype=np.float32)

    for column in df.columns:
        if "probs" not in column: continue

        df[column] = df[column].apply(cast_array) # type: ignore

    return df


dataset_clustered_primal_to_dataset_clustered_final = {
    "original": get_processing([
        add_probs_tabular_evaluation,
        add_probs_tabular_behavior_original,
        add_terminal_transition,
    ]),
    "exploratory": get_processing([
        add_probs_tabular_evaluation,
        add_probs_tabular_behavior_exploratory,
        add_terminal_transition,
    ]),
    "evaluation": get_processing([
        add_probs_tabular_evaluation,
        add_terminal_transition,
    ]),
}

In [ ]:
def get_dataset_clustered_final_(name):
    if name == "original":
        return get_dataset_from_df(
            dir=dir_clustering,
            df=dataset["tabular"]["clustered_primal"]["test"],
            hyperparameters={
                "evaluation_policy": {
                    "id": id_policy["tabular"]["evaluation"], # type: ignore
                },
            },
            postprocessing=dataset_clustered_primal_to_dataset_clustered_final[name],
            verbosity=1,
        )

    if name in ["exploratory", "evaluation"]:
        return get_dataset_from_env(
            dir=dir_policy["tabular"][name],
            env=env["test"][""],
            get_act=get_act[name],
            hyperparameters={
                "n_trajectories": n_trajectories,
                "max_trajectory_length": max_trajectory_length,
                "seed": seed,
                "evaluation_policy": {
                    "id": id_policy["tabular"]["evaluation"], # type: ignore
                },
            },
            postprocessing=dataset_clustered_primal_to_dataset_clustered_final[name],
            verbosity=1,
        )
    
    raise ValueError

def get_dataset_clustered_final():
    dataset_clustered_final = {}
    id_dataset = {}

    for name in names:
        x, y = get_dataset_clustered_final_(name)
        dataset_clustered_final[name] = x
        id_dataset[name] = y

    return dataset_clustered_final, id_dataset

In [42]:
dataset["tabular"]["clustered_final"], id_dataset["tabular"] = get_dataset_clustered_final()

trying to find id_dataset in data/medical_rl/sepsis_bologheanu/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/dataset.json
trying to load dataset from data/medical_rl/sepsis_bologheanu/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/2025-04-04T14:36:57.598315/dataset.parquet
trying to find id_dataset in data/medical_rl/sepsis_bologheanu/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/2025-04-04T14:16:14.383206/dataset.json
trying to load dataset from data/medical_rl/sepsis_bologheanu/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/2025-04-04T14:16:14.383206/2025-04-04T14:37:38.614841/dataset.parquet
trying to find id_dataset in data/medical_rl/sepsis_bologheanu/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/2025-04-04T14:20:10.762120/dataset.json
trying to load dataset from data/medical_rl/sepsis_bologheanu/2025-01-30T11:42:45.694984/2025-01-30T12:01:58.273325/2025-04-04T14:20:10.762120/2025-04-04T14:40:16.046389/dataset.parquet

In [43]:
for k, v in dataset["tabular"]["clustered_final"].items():
    print(f"{k=}")
    display(head_by_id(v, n=2))

k='original'

,id,t,obs_init,obs,act,rew,obs_next,probs_init,probs,probs_next,probs_behavior_init,probs_behavior,probs_behavior_next
0,20,0,58,58,1,0.0,179,"[0.016237022, 0.0014849559, 0.6178519, 0.30005...","[0.016237022, 0.0014849559, 0.6178519, 0.30005...","[0.0009460958, 0.98486024, 0.00033117103, 0.00...","[0.64220184, 0.09633028, 0.07798165, 0.1422018...","[0.64220184, 0.09633028, 0.07798165, 0.1422018...","[0.5987261, 0.18152866, 0.05732484, 0.10509554..."
1,20,1,58,179,1,0.0,17,"[0.016237022, 0.0014849559, 0.6178519, 0.30005...","[0.0009460958, 0.98486024, 0.00033117103, 0.00...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.64220184, 0.09633028, 0.07798165, 0.1422018...","[0.5987261, 0.18152866, 0.05732484, 0.10509554...","[0.64451313, 0.1576507, 0.038639877, 0.1112828..."
2,20,2,58,17,1,0.0,17,"[0.016237022, 0.0014849559, 0.6178519, 0.30005...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.64220184, 0.09633028, 0.07798165, 0.1422018...","[0.64451313, 0.1576507, 0.038639877, 0.1112828...","[0.64451313, 0.1576507, 0.038639877, 0.1112828..."
3,20,3,58,17,1,0.0,17,"[0.016237022, 0.0014849559, 0.6178519, 0.30005...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.64220184, 0.09633028, 0.07798165, 0.1422018...","[0.64451313, 0.1576507, 0.038639877, 0.1112828...","[0.64451313, 0.1576507, 0.038639877, 0.1112828..."
4,20,4,58,17,1,0.0,17,"[0.016237022, 0.0014849559, 0.6178519, 0.30005...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.64220184, 0.09633028, 0.07798165, 0.1422018...","[0.64451313, 0.1576507, 0.038639877, 0.1112828...","[0.64451313, 0.1576507, 0.038639877, 0.1112828..."
5,20,5,58,17,1,0.0,17,"[0.016237022, 0.0014849559, 0.6178519, 0.30005...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.64220184, 0.09633028, 0.07798165, 0.1422018...","[0.64451313, 0.1576507, 0.038639877, 0.1112828...","[0.64451313, 0.1576507, 0.038639877, 0.1112828..."
6,20,6,58,17,1,0.0,256,"[0.016237022, 0.0014849559, 0.6178519, 0.30005...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.099401385, 0.08730502, 0.018886177, 0.36740...","[0.64220184, 0.09633028, 0.07798165, 0.1422018...","[0.64451313, 0.1576507, 0.038639877, 0.1112828...","[0.2, 0.2, 0.2, 0.2, 0.2]"
7,20,7,58,256,4,0.0,256,"[0.016237022, 0.0014849559, 0.6178519, 0.30005...","[0.099401385, 0.08730502, 0.018886177, 0.36740...","[0.099401385, 0.08730502, 0.018886177, 0.36740...","[0.64220184, 0.09633028, 0.07798165, 0.1422018...","[0.2, 0.2, 0.2, 0.2, 0.2]","[0.2, 0.2, 0.2, 0.2, 0.2]"
8,25,0,254,254,2,0.0,254,"[0.03472524, 0.033255864, 0.9320189, 0.0, 0.0]","[0.03472524, 0.033255864, 0.9320189, 0.0, 0.0]","[0.03472524, 0.033255864, 0.9320189, 0.0, 0.0]","[0.6666667, 0.16666667, 0.16666667, 0.0, 0.0]","[0.6666667, 0.16666667, 0.16666667, 0.0, 0.0]","[0.6666667, 0.16666667, 0.16666667, 0.0, 0.0]"
9,25,1,254,254,2,1.0,257,"[0.03472524, 0.033255864, 0.9320189, 0.0, 0.0]","[0.03472524, 0.033255864, 0.9320189, 0.0, 0.0]","[0.019111522, 0.31436116, 0.07228454, 0.422952...","[0.6666667, 0.16666667, 0.16666667, 0.0, 0.0]","[0.6666667, 0.16666667, 0.16666667, 0.0, 0.0]","[0.2, 0.2, 0.2, 0.2, 0.2]"
10,25,2,254,257,3,0.0,257,"[0.03472524, 0.033255864, 0.9320189, 0.0, 0.0]","[0.019111522, 0.31436116, 0.07228454, 0.422952...","[0.019111522, 0.31436116, 0.07228454, 0.422952...","[0.6666667, 0.16666667, 0.16666667, 0.0, 0.0]","[0.2, 0.2, 0.2, 0.2, 0.2]","[0.2, 0.2, 0.2, 0.2, 0.2]"

k='exploratory'

,id,t,obs_init,obs,act,rew,obs_next,probs_init,probs,probs_next,probs_behavior_init,probs_behavior,probs_behavior_next
0,0,0,97,97,1,0,42,"[0.023121499, 0.018567674, 0.5829504, 0.041359...","[0.023121499, 0.018567674, 0.5829504, 0.041359...","[0.010555702, 0.26572725, 0.5671722, 0.1290787...","[0.1389955, 0.20588483, 0.41373006, 0.15858203...","[0.1389955, 0.20588483, 0.41373006, 0.15858203...","[0.11260244, 0.33042437, 0.27037343, 0.1280402..."
1,0,1,97,42,3,1,257,"[0.023121499, 0.018567674, 0.5829504, 0.041359...","[0.010555702, 0.26572725, 0.5671722, 0.1290787...","[0.019111522, 0.31436116, 0.07228454, 0.422952...","[0.1389955, 0.20588483, 0.41373006, 0.15858203...","[0.11260244, 0.33042437, 0.27037343, 0.1280402...","[0.16155878, 0.2706891, 0.13586152, 0.22651583..."
2,0,2,97,257,3,0,257,"[0.023121499, 0.018567674, 0.5829504, 0.041359...","[0.019111522, 0.31436116, 0.07228454, 0.422952...","[0.019111522, 0.31436116, 0.07228454, 0.422952...","[0.1389955, 0.20588483, 0.41373006, 0.15858203...","[0.16155878, 0.2706891, 0.13586152, 0.22651583...","[0.16155878, 0.2706891, 0.13586152, 0.22651583..."
3,1,0,144,144,0,0,144,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.36340088, 0.14329387, 0.11220293, 0.2480995...","[0.36340088, 0.14329387, 0.11220293, 0.2480995...","[0.36340088, 0.14329387, 0.11220293, 0.2480995..."
4,1,1,144,144,1,0,144,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.36340088, 0.14329387, 0.11220293, 0.2480995...","[0.36340088, 0.14329387, 0.11220293, 0.2480995...","[0.36340088, 0.14329387, 0.11220293, 0.2480995..."
5,1,2,144,144,0,0,247,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0012141267, 0.0132386, 0.6461953, 0.2690848...","[0.36340088, 0.14329387, 0.11220293, 0.2480995...","[0.36340088, 0.14329387, 0.11220293, 0.2480995...","[0.08255359, 0.22748806, 0.25635046, 0.2646325..."
6,1,3,144,247,0,0,44,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0012141267, 0.0132386, 0.6461953, 0.2690848...","[0.01352798, 0.012362986, 0.007120129, 0.82230...","[0.36340088, 0.14329387, 0.11220293, 0.2480995...","[0.08255359, 0.22748806, 0.25635046, 0.2646325...","[0.13159919, 0.16863076, 0.13916346, 0.3634553..."
7,1,4,144,44,3,0,247,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.01352798, 0.012362986, 0.007120129, 0.82230...","[0.0012141267, 0.0132386, 0.6461953, 0.2690848...","[0.36340088, 0.14329387, 0.11220293, 0.2480995...","[0.13159919, 0.16863076, 0.13916346, 0.3634553...","[0.08255359, 0.22748806, 0.25635046, 0.2646325..."
8,1,5,144,247,2,0,44,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0012141267, 0.0132386, 0.6461953, 0.2690848...","[0.01352798, 0.012362986, 0.007120129, 0.82230...","[0.36340088, 0.14329387, 0.11220293, 0.2480995...","[0.08255359, 0.22748806, 0.25635046, 0.2646325...","[0.13159919, 0.16863076, 0.13916346, 0.3634553..."
9,1,6,144,44,1,0,44,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.01352798, 0.012362986, 0.007120129, 0.82230...","[0.01352798, 0.012362986, 0.007120129, 0.82230...","[0.36340088, 0.14329387, 0.11220293, 0.2480995...","[0.13159919, 0.16863076, 0.13916346, 0.3634553...","[0.13159919, 0.16863076, 0.13916346, 0.3634553..."
10,1,7,144,44,2,0,208,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.01352798, 0.012362986, 0.007120129, 0.82230...","[0.0013184386, 0.98639995, 0.0007456495, 0.008...","[0.36340088, 0.14329387, 0.11220293, 0.2480995...","[0.13159919, 0.16863076, 0.13916346, 0.3634553...","[0.29325175, 0.33629936, 0.10360184, 0.1532773..."
11,1,8,144,208,2,1,257,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0013184386, 0.98639995, 0.0007456495, 0.008...","[0.019111522, 0.31436116, 0.07228454, 0.422952...","[0.36340088, 0.14329387, 0.11220293, 0.2480995...","[0.29325175, 0.33629936, 0.10360184, 0.1532773...","[0.16155878, 0.2706891, 0.13586152, 0.22651583..."
12,1,9,144,257,3,0,257,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.019111522, 0.31436116, 0.07228454, 0.422952...","[0.019111522, 0.31436116, 0.07228454, 0.422952...","[0.36340088, 0.14329387, 0.11220293, 0.2480995...","[0.16155878, 0.2706891, 0.13586152, 0.22651583...","[0.16155878, 0.2706891, 0.13586152, 0.22651583..."

k='evaluation'

,id,t,obs_init,obs,act,rew,obs_next,probs_init,probs,probs_next
0,0,0,97,97,2,0,104,"[0.023121499, 0.018567674, 0.5829504, 0.041359...","[0.023121499, 0.018567674, 0.5829504, 0.041359...","[0.034258768, 0.008222747, 0.0464423, 0.911076..."
1,0,1,97,104,3,0,24,"[0.023121499, 0.018567674, 0.5829504, 0.041359...","[0.034258768, 0.008222747, 0.0464423, 0.911076...","[0.0048171766, 0.91280186, 0.07493122, 0.00744..."
2,0,2,97,24,1,0,122,"[0.023121499, 0.018567674, 0.5829504, 0.041359...","[0.0048171766, 0.91280186, 0.07493122, 0.00744...","[0.0018074316, 0.86823225, 0.09632578, 0.03036..."
3,0,3,97,122,1,0,244,"[0.023121499, 0.018567674, 0.5829504, 0.041359...","[0.0018074316, 0.86823225, 0.09632578, 0.03036...","[0.007445688, 0.09870003, 0.7324922, 0.0280044..."
4,0,4,97,244,4,0,244,"[0.023121499, 0.018567674, 0.5829504, 0.041359...","[0.007445688, 0.09870003, 0.7324922, 0.0280044...","[0.007445688, 0.09870003, 0.7324922, 0.0280044..."
5,0,5,97,244,2,0,48,"[0.023121499, 0.018567674, 0.5829504, 0.041359...","[0.007445688, 0.09870003, 0.7324922, 0.0280044...","[0.07213532, 0.022990702, 0.15267873, 0.040649..."
6,0,6,97,48,4,0,256,"[0.023121499, 0.018567674, 0.5829504, 0.041359...","[0.07213532, 0.022990702, 0.15267873, 0.040649...","[0.099401385, 0.08730502, 0.018886177, 0.36740..."
7,0,7,97,256,3,0,256,"[0.023121499, 0.018567674, 0.5829504, 0.041359...","[0.099401385, 0.08730502, 0.018886177, 0.36740...","[0.099401385, 0.08730502, 0.018886177, 0.36740..."
8,1,0,144,144,2,0,247,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0012141267, 0.0132386, 0.6461953, 0.2690848..."
9,1,1,144,247,2,0,247,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0012141267, 0.0132386, 0.6461953, 0.2690848...","[0.0012141267, 0.0132386, 0.6461953, 0.2690848..."
10,1,2,144,247,2,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0012141267, 0.0132386, 0.6461953, 0.2690848...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
11,1,3,144,153,1,0,40,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.018189415, 0.25201485, 0.35578638, 0.297780..."
12,1,4,144,40,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.018189415, 0.25201485, 0.35578638, 0.297780...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
13,1,5,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
14,1,6,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
15,1,7,144,153,3,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
16,1,8,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
17,1,9,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
18,1,10,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
19,1,11,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
20,1,12,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
21,1,13,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
22,1,14,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
23,1,15,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
24,1,16,144,153,2,0,40,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.018189415, 0.25201485, 0.35578638, 0.297780..."
25,1,17,144,40,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.018189415, 0.25201485, 0.35578638, 0.297780...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
26,1,18,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
27,1,19,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
28,1,20,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
29,1,21,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
30,1,22,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
31,1,23,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
32,1,24,144,153,1,0,105,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0014564948, 0.6779344, 0.27459684, 0.017152..."
33,1,25,144,105,2,0,140,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0014564948, 0.6779344, 0.27459684, 0.017152...","[0.0025909427, 0.97324276, 0.0032926323, 0.020..."
34,1,26,144,140,1,0,105,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0025909427, 0.97324276, 0.0032926323, 0.020...","[0.0014564948, 0.6779344, 0.27459684, 0.017152..."
35,1,27,144,105,1,0,105,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0014564948, 0.6779344, 0.27459684, 0.017152...","[0.0014564948, 0.6779344, 0.27459684, 0.017152..."
36,1,28,144,105,1,0,105,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0014564948, 0.6779344, 0.27459684, 0.017152...","[0.0014564948, 0.6779344, 0.27459684, 0.017152..."
37,1,29,144,105,1,0,44,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0014564948, 0.6779344, 0.27459684, 0.017152...","[0.01352798, 0.012362986, 0.007120129, 0.82230..."
38,1,30,144,44,3,0,44,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.01352798, 0.012362986, 0.007120129, 0.82230...","[0.01352798, 0.012362986, 0.007120129, 0.82230..."
39,1,31,144,44,3,0,44,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.01352798, 0.012362986, 0.007120129, 0.82230...","[0.01352798, 0.012362986, 0.007120129, 0.82230..."
40,1,32,144,44,4,0,44,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.01352798, 0.012362986, 0.007120129, 0.82230...","[0.01352798, 0.012362986, 0.007120129, 0.82230..."
41,1,33,144,44,3,0,44,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.01352798, 0.012362986, 0.007120129, 0.82230...","[0.01352798, 0.012362986, 0.007120129, 0.82230..."
42,1,34,144,44,3,0,145,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.01352798, 0.012362986, 0.007120129, 0.82230...","[0.009095079, 0.47466585, 0.41821086, 0.036357..."
43,1,35,144,145,1,0,145,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.009095079, 0.47466585, 0.41821086, 0.036357...","[0.009095079, 0.47466585, 0.41821086, 0.036357..."
44,1,36,144,145,1,0,52,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.009095079, 0.47466585, 0.41821086, 0.036357...","[0.0032612805, 0.08743155, 0.0044781924, 0.592..."
45,1,37,144,52,3,0,52,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0032612805, 0.08743155, 0.0044781924, 0.592...","[0.0032612805, 0.08743155, 0.0044781924, 0.592..."
46,1,38,144,52,4,0,52,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0032612805, 0.08743155, 0.0044781924, 0.592...","[0.0032612805, 0.08743155, 0.0044781924, 0.592..."
47,1,39,144,52,3,0,145,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0032612805, 0.08743155, 0.0044781924, 0.592...","[0.009095079, 0.47466585, 0.41821086, 0.036357..."
48,1,40,144,145,1,0,145,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.009095079, 0.47466585, 0.41821086, 0.036357...","[0.009095079, 0.47466585, 0.41821086, 0.036357..."
49,1,41,144,145,1,0,44,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.009095079, 0.47466585, 0.41821086, 0.036357...","[0.01352798, 0.012362986, 0.007120129, 0.82230..."
50,1,42,144,44,3,0,183,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.01352798, 0.012362986, 0.007120129, 0.82230...","[0.08129628, 0.34804747, 0.009817343, 0.051257..."
51,1,43,144,183,4,0,183,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.08129628, 0.34804747, 0.009817343, 0.051257...","[0.08129628, 0.34804747, 0.009817343, 0.051257..."
52,1,44,144,183,4,0,183,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.08129628, 0.34804747, 0.009817343, 0.051257...","[0.08129628, 0.34804747, 0.009817343, 0.051257..."
53,1,45,144,183,1,0,183,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.08129628, 0.34804747, 0.009817343, 0.051257...","[0.08129628, 0.34804747, 0.009817343, 0.051257..."
54,1,46,144,183,4,0,183,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.08129628, 0.34804747, 0.009817343, 0.051257...","[0.08129628, 0.34804747, 0.009817343, 0.051257..."
55,1,47,144,183,1,0,52,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.08129628, 0.34804747, 0.009817343, 0.051257...","[0.0032612805, 0.08743155, 0.0044781924, 0.592..."
56,1,48,144,52,3,0,52,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0032612805, 0.08743155, 0.0044781924, 0.592...","[0.0032612805, 0.08743155, 0.0044781924, 0.592..."
57,1,49,144,52,3,0,52,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0032612805, 0.08743155, 0.0044781924, 0.592...","[0.0032612805, 0.08743155, 0.0044781924, 0.592..."
58,1,50,144,52,4,0,52,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0032612805, 0.08743155, 0.0044781924, 0.592...","[0.0032612805, 0.08743155, 0.0044781924, 0.592..."
59,1,51,144,52,4,0,52,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0032612805, 0.08743155, 0.0044781924, 0.592...","[0.0032612805, 0.08743155, 0.0044781924, 0.592..."
60,1,52,144,52,2,0,52,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0032612805, 0.08743155, 0.0044781924, 0.592...","[0.0032612805, 0.08743155, 0.0044781924, 0.592..."
61,1,53,144,52,4,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0032612805, 0.08743155, 0.0044781924, 0.592...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
62,1,54,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
63,1,55,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
64,1,56,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
65,1,57,144,153,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
66,1,58,144,153,1,0,40,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.018189415, 0.25201485, 0.35578638, 0.297780..."
67,1,59,144,40,1,0,153,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.018189415, 0.25201485, 0.35578638, 0.297780...","[0.0011117996, 0.9172882, 0.049956456, 0.02195..."
68,1,60,144,153,2,1,257,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.0011117996, 0.9172882, 0.049956456, 0.02195...","[0.019111522, 0.31436116, 0.07228454, 0.422952..."
69,1,61,144,257,1,0,257,"[0.077239595, 0.26684684, 0.2533386, 0.4010225...","[0.019111522, 0.31436116, 0.07228454, 0.422952...","[0.019111522, 0.31436116, 0.07228454, 0.422952..."

In [44]:
display(
    assertion_terminal(dataset["tabular"]["clustered_final"]["original"], 7) and \
    assertion_terminal(dataset["tabular"]["clustered_final"]["original"], 10)
)

display(
    assertion_terminal(dataset["tabular"]["clustered_final"]["exploratory"], 2) and \
    assertion_terminal(dataset["tabular"]["clustered_final"]["exploratory"], 6)
)

display(
    assertion_terminal(dataset["tabular"]["clustered_final"]["evaluation"], 3) and \
    assertion_terminal(dataset["tabular"]["clustered_final"]["evaluation"], 43)
)

True

True

True

# Continuous

In [45]:
dataset["continuous"] = {}

In [ ]:
model["continuous"] = Model(5, 1024)
model["continuous"].load_weights( os.path.join(dir_policy["continuous"]["neural"], f"policy.h5"))

## Neural

### Datset

In [ ]:
def dataset_raw_to_RL_split(dataset_raw):
    RL_split = AmsterdamFormatter().RL_split(dataset_raw)
    return RL_split

In [ ]:
def dataset_raw_to_dataset_primal(dataset_raw):
    RL_split = dataset_raw_to_RL_split(dataset_raw)
    dataset_primal = RL_split_to_dataset_primal(RL_split, tabular=False)

    return dataset_primal

In [ ]:
head_by_id(
    dataset_raw_to_dataset_primal(
        load_datasets_raw()["test"]
    ),
    n=2,
)

,id,t,obs_init,obs,act,rew,obs_next
0,20,0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254..."
1,20,1,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254..."
2,20,2,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254..."
3,20,3,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254..."
4,20,4,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254..."
5,20,5,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254..."
6,20,6,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254..."
7,25,0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",2,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254..."
8,25,1,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",2,1.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254..."

In [50]:
# final processing

def get_probs_AmsterdamA2C(observation):
    o = observation
    o = list(o)
    o = tf.convert_to_tensor(o, tf.float32)

    l, _ = model["continuous"](o)
    p = tf.nn.softmax(l, axis=1)
    p = np.array(p)

    return p

def add_probs_continuous(df):
    df = df.copy(deep=False)
    df["probs_init"] = list( get_probs_AmsterdamA2C(df["obs_init"]) )
    df["probs"]      = list( get_probs_AmsterdamA2C(df["obs"]) )
    df["probs_next"] = list( get_probs_AmsterdamA2C(df["obs_next"]) )
    return df

dataset_primal_to_dataset_final = get_processing([
    add_probs_continuous,
    add_terminal_transition,
])

In [51]:
head_by_id(
    dataset_primal_to_dataset_final(
        dataset_raw_to_dataset_primal(
            load_datasets_raw()["test"]
        )
    ),
    n=2,
)

,id,t,obs_init,obs,act,rew,obs_next,probs_init,probs,probs_next
0,20,0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[4.6153204e-07, 0.41843063, 0.09803962, 0.2416..."
1,20,1,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[4.6153204e-07, 0.41843063, 0.09803962, 0.2416...","[1.3341968e-18, 0.99022615, 0.0011949288, 0.00..."
2,20,2,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[1.3341968e-18, 0.99022615, 0.0011949288, 0.00...","[4.3437872e-23, 0.99479574, 5.7580583e-06, 0.0..."
3,20,3,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[4.3437872e-23, 0.99479574, 5.7580583e-06, 0.0...","[9.325621e-10, 0.00401068, 0.008864737, 0.9811..."
4,20,4,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[9.325621e-10, 0.00401068, 0.008864737, 0.9811...","[4.656923e-15, 6.592461e-05, 0.0002901405, 0.9..."
5,20,5,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[4.656923e-15, 6.592461e-05, 0.0002901405, 0.9...","[2.4188708e-07, 8.889674e-06, 0.00064626464, 0..."
6,20,6,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[2.4188708e-07, 8.889674e-06, 0.00064626464, 0...","[0.0, 1.0, 9.294034e-10, 3.452601e-08, 7.56487..."
7,20,7,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[0.0, 1.0, 9.294034e-10, 3.452601e-08, 7.56487...","[0.0, 1.0, 9.294034e-10, 3.452601e-08, 7.56487..."
8,25,0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",2,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[4.83073e-08, 7.87445e-06, 0.07960352, 0.91251...","[4.83073e-08, 7.87445e-06, 0.07960352, 0.91251...","[1.7647663e-11, 1.2354242e-06, 0.002096404, 0...."
9,25,1,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",2,1.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[4.83073e-08, 7.87445e-06, 0.07960352, 0.91251...","[1.7647663e-11, 1.2354242e-06, 0.002096404, 0....","[5.115847e-25, 0.00045865908, 0.0034875793, 0...."
10,25,2,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",3,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[4.83073e-08, 7.87445e-06, 0.07960352, 0.91251...","[5.115847e-25, 0.00045865908, 0.0034875793, 0....","[5.115847e-25, 0.00045865908, 0.0034875793, 0...."

In [58]:
def assertion_probs(df, column, tol=1e-6):
    for i in range( len(df) ):
        S = np.sum(df.loc[i, column])
        assert np.abs(S-1) < tol, S

In [59]:
def get_dataset_continuous():
    datasets_raw = load_datasets_raw()
    dataset_raw  = datasets_raw["test"]

    dataset_primal = dataset_raw_to_dataset_primal(dataset_raw)
    dataset_final  = dataset_primal_to_dataset_final(dataset_primal)

    for column in ["probs_init", "probs", "probs_next"]:
        assertion_probs(dataset_final, column)

    dataset_continuous = {
        "raw": dataset_raw,
        "primal": dataset_primal,
        "final": dataset_final,
    }

    return dataset_continuous

In [60]:
dataset["continuous"]["neural"] = get_dataset_continuous()

In [61]:
dataset["continuous"]["neural"]["final"].to_parquet(
    os.path.join(dir_dataset["continuous"], f"dataset.parquet"), )

In [62]:
head_by_id(dataset["continuous"]["neural"]["final"], n=2)

,id,t,obs_init,obs,act,rew,obs_next,probs_init,probs,probs_next
0,20,0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[4.6153204e-07, 0.41843063, 0.09803962, 0.2416..."
1,20,1,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[4.6153204e-07, 0.41843063, 0.09803962, 0.2416...","[1.3341968e-18, 0.99022615, 0.0011949288, 0.00..."
2,20,2,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[1.3341968e-18, 0.99022615, 0.0011949288, 0.00...","[4.3437872e-23, 0.99479574, 5.7580583e-06, 0.0..."
3,20,3,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[4.3437872e-23, 0.99479574, 5.7580583e-06, 0.0...","[9.325621e-10, 0.00401068, 0.008864737, 0.9811..."
4,20,4,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[9.325621e-10, 0.00401068, 0.008864737, 0.9811...","[4.656923e-15, 6.592461e-05, 0.0002901405, 0.9..."
5,20,5,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[4.656923e-15, 6.592461e-05, 0.0002901405, 0.9...","[2.4188708e-07, 8.889674e-06, 0.00064626464, 0..."
6,20,6,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[2.4188708e-07, 8.889674e-06, 0.00064626464, 0...","[0.0, 1.0, 9.294034e-10, 3.452601e-08, 7.56487..."
7,20,7,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[0.0, 1.0, 9.294034e-10, 3.452601e-08, 7.56487...","[0.0, 1.0, 9.294034e-10, 3.452601e-08, 7.56487..."
8,25,0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",2,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[4.83073e-08, 7.87445e-06, 0.07960352, 0.91251...","[4.83073e-08, 7.87445e-06, 0.07960352, 0.91251...","[1.7647663e-11, 1.2354242e-06, 0.002096404, 0...."
9,25,1,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",2,1.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[4.83073e-08, 7.87445e-06, 0.07960352, 0.91251...","[1.7647663e-11, 1.2354242e-06, 0.002096404, 0....","[5.115847e-25, 0.00045865908, 0.0034875793, 0...."
10,25,2,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",3,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[4.83073e-08, 7.87445e-06, 0.07960352, 0.91251...","[5.115847e-25, 0.00045865908, 0.0034875793, 0....","[5.115847e-25, 0.00045865908, 0.0034875793, 0...."

In [63]:
assertion_terminal(dataset["continuous"]["neural"]["final"], 7) and \
assertion_terminal(dataset["continuous"]["neural"]["final"], 10)

True

### Bounds

In [ ]:
def load_bounds_raw():
    return AmsterdamFormatter() \
        .load_bounds(dir_split)

In [ ]:
load_bounds_raw()

,ID,Length of Stay,ACTH max,ACTH mean,ACTH min,ACTH std,AF Monitor max,AF Monitor mean,AF Monitor min,AF Monitor std,...,Fluid balance,AdmissionCount,Steroids,SOFA score,Age,Gender,Antibiotics,Antiviral,Antifungal,ICU Mortality
0,23545.0,1000,56.942379,27.410480,27.405037,2.410966,8.480442,14.704375,14.351298,2.343781,...,14.141715,11.421480,1.0,3.787396,5,2,3,1,1,1
1,11.0,0,-0.806916,-0.954016,-0.953790,-0.025408,-2.328308,-2.446705,-1.451279,-1.456343,...,-6.285162,-0.271663,0.0,-1.969128,0,0,0,0,0,0

In [ ]:
def bounds_raw_to_bounds_final(bounds_raw):
    bounds_raw_dropped = bounds_raw.drop(
        columns=["ID", "Length of Stay", "Steroids", "ICU Mortality"])

    bounds = {
        "obs_max": np.array(bounds_raw_dropped.loc[0]),
        "obs_min": np.array(bounds_raw_dropped.loc[1]),
    }

    return bounds

In [ ]:
bounds_raw_to_bounds_final(load_bounds_raw())

{'obs_min': array([ 5.69423790e+01,  2.74104805e+01,  2.74050369e+01,  2.41096640e+00,
         8.48044205e+00,  1.47043753e+01,  1.43512983e+01,  2.34378076e+00,
         2.12411346e+01,  2.77196846e+01,  2.83973942e+01,  1.25085926e+00,
         4.95312119e+00,  5.04160357e+00,  5.04312611e+00,  3.50155783e+00,
         3.08868542e+01,  3.29250221e+01,  3.44894981e+01, -2.00814128e+00,
         2.74480343e+01,  2.14069958e+01,  2.07772083e+01,  5.10954618e-01,
         8.80081081e+00,  1.09015923e+01,  1.79302856e-01,  1.64076187e+02,
         2.00921219e+02,  2.06600082e+02,  1.00391424e+00,  5.10706177e+01,
         4.57524920e+00,  5.58103991e+00,  4.78265643e-01,  2.65454044e+01,
         2.70125237e+01,  2.74020386e+01,  2.39406729e+00,  5.19698048e+00,
         5.49257851e+00,  5.34956837e+00, -5.68367660e-01,  9.14467087e+01,
         2.24091644e+02,  8.96394897e+02, -4.63353023e-02,  1.30696144e+01,
         1.30436869e+01,  1.30009518e+01, -4.32487205e-02,  7.78269434e+00,
         6.25319290e+01,  2.18146634e+00,  1.06671691e-01,  1.46859512e+01,
         2.23257961e+01,  1.97080898e+01, -9.23389614e-01,  1.56969824e+01,
         1.78252239e+01,  1.13902626e+01,  5.27258539e+00,  2.81011581e+01,
         2.81011581e+01,  2.81011581e+01,  0.00000000e+00,  2.10119724e+00,
         6.23745632e+00,  8.74369431e+00,  5.87125111e+00,  2.91534386e+01,
         2.91534386e+01,  2.91534386e+01, -5.50895643e+00,  5.49852638e+01,
         7.17274017e+01,  6.45217056e+01, -1.21497005e-01,  3.43456612e+01,
         3.58067169e+01,  3.58667946e+01,  2.05239430e-01,  2.89285980e+02,
         4.72231232e+02,  5.02649445e+02,  7.65155792e+00,  8.68973064e+00,
         8.68822098e+00,  8.68112659e+00, -9.03221518e-02,  2.43684273e+01,
         2.43684273e+01,  2.43684273e+01,  8.25622131e+02,  9.08070278e+00,
         1.32801390e+01,  1.40495453e+01,  5.89036793e-02,  9.54304218e+00,
         1.38338118e+01,  3.56082611e+01,  1.58197030e-01,  1.44770155e+01,
         1.43669586e+01,  1.40461807e+01, -4.34029341e-01,  9.92143707e+01,
         4.18384857e+02,  5.54384277e+02,  9.41713905e+00,  4.65795898e+01,
         5.36320343e+01,  5.98604164e+01, -9.79677122e-03,  1.98678875e+01,
         1.98560848e+01,  1.98207359e+01,  2.18185196e+02,  4.35507965e+01,
         5.38658981e+01,  6.26580200e+01,  2.13624716e+00,  9.40452957e+01,
         1.26229713e+02,  1.75076324e+02, -8.95343423e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  2.00000000e+00,  2.72193794e+01,
         2.81935158e+01,  2.71267948e+01,  1.36786535e-01,  6.75634384e+01,
         6.76088181e+01,  6.76184692e+01,  2.24757118e+01,  8.29252720e+00,
         8.32817364e+00,  8.36157608e+00, -1.65630257e+00,  8.43681812e+00,
         8.44421101e+00,  8.44006157e+00,  1.65787673e+00,  7.41748123e+01,
         1.22292995e+01,  7.01904249e+00,  2.15376878e+00,  6.43598938e+01,
         1.44230509e+01,  9.71892548e+00,  3.43273431e-02,  5.26289978e+02,
         2.99263363e+01,  5.09942818e+00,  5.80680251e-01,  3.64133334e+00,
         3.64026284e+00,  3.64027286e+00,  4.61370945e+00,  9.66327362e+01,
         2.10799427e+01,  2.18883495e+01,  1.97419941e-01,  1.60614059e+02,
         2.30938919e+02,  2.30938919e+02,  4.88702822e+00,  7.00250473e+01,
         5.19924498e+00,  5.65238285e+00,  9.23804224e-01,  9.64911461e+00,
         1.60534496e+01,  8.03078175e+00,  7.09629536e-01,  8.38449287e+00,
         1.18033152e+01,  1.42528057e+01,  1.84893394e+00,  1.20461937e+02,
         7.97444439e+00,  8.64901447e+00,  1.37855506e+00,  1.44602402e+02,
         5.63911133e+01,  2.35563793e+01,  8.88098180e-01,  5.90954323e+01,
         8.20490189e+01,  8.84122772e+01,  1.54883873e+00,  7.50093307e+01,
         4.38511162e+01,  6.01967278e+01, -9.57863390e-01,  5.42773771e+00,
         5.61149979e+00,  5.59368181e+00,  2.39492702e+01,  4.74434423e+00,
         2.32378769e+01,  2.13633671e+01, -5.45882620e-03,  1.82669220e+01,
         2.03377647e+01,  2.12256336e+01,  3.69333839e+00,  6.18368292e+00,
         1.73862610e+01,  1.51545353e+01,  7.20370635e-02,  1.29714270e+01,
         1.42515469e+01,  1.48512478e+01,  4.66236734e+00,  3.53392363e+00,
         8.56203938e+00,  8.69418812e+00,  1.33801982e-01,  6.77092648e+00,
         7.53686619e+00,  7.87289667e+00,  6.45734978e+00,  1.42445526e+01,
         4.81249733e+01,  6.96763306e+01,  3.34651146e+01,  1.67453194e+00,
         4.67558002e+00,  3.93793166e-01,  5.01180530e-01,  9.18213308e-01,
         2.93527126e-01,  1.02420604e+00,  9.86259937e-01,  3.15995097e+00,
         2.63598576e+01,  2.63965950e+01,  2.63427238e+01,  1.00632830e+01,
         1.66529427e+01,  1.95564003e+01,  6.18239307e+00,  4.20221519e+00,
         6.35722685e+00,  6.72643375e+00,  6.37165642e+00,  5.88033080e-01,
         1.27468004e+01,  1.28180761e+01,  1.27932663e+01,  1.27508980e+02,
         1.23752375e+01,  1.16687002e+01,  9.95166588e+00, -2.17201376e+00,
         1.14904175e+01,  1.13854942e+01,  1.09861917e+01, -3.37522292e+00,
         1.62216454e+01,  8.58332348e+00,  8.54451942e+00, -2.13025546e+00,
         1.60138836e+01,  1.56824093e+01,  1.57780647e+01, -6.57141209e-02,
         7.72540617e+00,  7.36884689e+00,  7.43273306e+00,  3.36522508e+00,
         1.32446289e+01,  2.81742744e+01,  4.93413162e+01,  4.05314970e+00,
         2.16798363e+01,  1.35357580e+01,  1.36497269e+01,  1.35246162e+01,
         3.25694203e+00,  2.10183735e+01,  2.10609722e+01,  2.10967789e+01,
        -4.26480696e-02,  5.13802567e+01,  0.00000000e+00, -4.85582161e+00,
        -4.67293784e-02,  3.78022919e+01,  2.07865295e+01,  1.91149597e+01,
         6.73431206e+00,  4.80527461e+04,  7.42500000e+03, -5.90619354e+01,
         3.73877406e-01,  3.77884064e+01,  4.13378410e+01,  4.16694565e+01,
         2.46955037e+00,  7.17814016e+00,  9.92934799e+01,  5.18125725e+01,
         5.12065697e+01,  2.12343712e+01,  5.26877701e-01,  3.84482819e+02,
         5.25738373e+01,  5.07118645e+01,  6.66499901e+00,  3.21282125e+00,
         5.85025883e+00,  7.18693466e+01,  9.51179123e+00,  6.06979828e+01,
         7.24121475e+01,  3.65272942e+01,  1.50615215e+01,  1.89794121e+01,
         9.97412300e+00,  1.86151295e+01,  1.29792662e+01,  1.77790489e+01,
         4.80539274e+00,  1.29984465e+01,  6.02207031e+01,  6.39846725e+01,
         2.87157078e+01,  5.62991440e-01,  1.34643345e+01,  7.06224442e+01,
         8.38240337e+00,  7.70152760e+00,  4.60407686e+00,  1.84070778e+01,
         1.62781315e+01,  9.98916626e+00,  1.88427124e+01,  2.55209656e+01,
         3.44033265e+00,  1.73368607e+01,  1.89851685e+01,  5.11193275e+00,
         1.86286221e+01,  1.30923786e+01,  4.38043118e+00,  2.82996106e+00,
         1.90970728e+03,  4.93536110e+01,  4.08263321e+01,  2.24814873e+01,
         2.19612098e+00,  3.08884048e+01,  3.50367661e+01,  7.26962852e+00,
         9.95413780e+00,  3.32226706e+00,  9.36134720e+00,  2.66583443e+01,
         1.24174366e+01,  1.42371502e+01,  1.87414894e+01,  2.59050293e+01,
         2.25968647e+01,  1.69497046e+03,  3.45058990e+00,  2.95292263e+01,
         1.22674713e+01,  3.06915140e+00,  1.41417150e+01,  1.14214802e+01,
         3.78739643e+00,  5.00000000e+00,  2.00000000e+00,  3.00000000e+00,
         1.00000000e+00,  1.00000000e+00]),
 'obs_max': array([-8.06915820e-01, -9.54015851e-01, -9.53790426e-01, -2.54084524e-02,
        -2.32830763e+00, -2.44670534e+00, -1.45127904e+00, -1.45634305e+00,
        -2.97194242e+00, -3.48733473e+00, -3.22874856e+00, -7.29413033e-01,
        -3.08796191e+00, -3.08928204e+00, -3.03649926e+00, -1.08392823e+00,
        -2.19888973e+00, -2.25506067e+00, -2.35733342e+00, -2.00814128e+00,
        -6.15756035e+00, -6.53796244e+00, -5.98751926e+00, -8.12110126e-01,
        -2.61270351e+01, -2.29396400e+01, -2.70833540e+00, -8.45425034e+00,
        -9.53036118e+00, -1.81086807e+01, -4.54230976e+00, -3.67017102e+00,
        -4.41145515e+00, -3.99905181e+00, -7.06714690e-01, -4.77863938e-01,
        -4.77305025e-01, -4.74949658e-01, -7.41412878e-01, -1.17235243e+00,
        -1.16939533e+00, -1.15859377e+00, -1.04782426e+00, -8.63174260e-01,
        -2.40820289e+00, -9.52082348e+00, -4.63353023e-02, -3.78860283e+00,
        -3.77877259e+00, -3.76478910e+00, -4.32487205e-02, -7.42801905e-01,
        -4.85994720e+00, -7.80608082e+00, -4.71839495e-02, -1.94620562e+00,
        -3.59345412e+00, -2.75349903e+00, -1.00415587e+00, -1.10821879e+00,
        -1.14049697e+00, -1.18284929e+00, -5.64071357e-01, -3.36050630e+00,
        -3.36050630e+00, -3.36050630e+00,  0.00000000e+00, -1.78177023e+00,
        -2.63522172e+00, -3.02552819e+00, -8.56090963e-01, -3.55314314e-02,
        -3.55303288e-02, -3.55292633e-02, -5.50895643e+00, -1.83581620e-01,
        -2.26875514e-01, -1.93393290e-01, -1.76160157e-01, -2.91009963e-01,
        -3.07688236e-01, -3.18200290e-01, -1.84086800e-01, -2.27874780e+00,
        -3.02083468e+00, -2.57567501e+00, -1.12813795e+00, -8.17834187e+00,
        -8.17556572e+00, -8.16753483e+00, -9.03221518e-02, -1.04616013e+01,
        -1.04616013e+01, -1.04616013e+01, -3.78641449e-02, -5.29186392e+00,
        -5.73906326e+00, -4.73980379e+00, -1.86346874e-01, -1.69378262e+01,
        -4.65805578e+00, -4.41035767e+01, -3.08572054e-01, -4.96249819e+00,
        -4.66725731e+00, -4.29626417e+00, -4.34029341e-01, -7.25996590e+00,
        -2.86308327e+01, -3.53951721e+01, -9.62077677e-01, -3.33899474e+00,
        -3.57710457e+00, -3.71765614e+00, -9.79677122e-03, -5.01324987e+00,
        -5.00841427e+00, -4.99831772e+00, -2.85352170e-02, -9.47036445e-01,
        -1.03930008e+00, -1.05834317e+00, -6.49953663e-01, -8.89832973e-02,
        -8.43996778e-02, -6.85402378e-02, -9.25584212e-02, -1.90000000e+01,
        -1.90000000e+01, -1.90000000e+01,  0.00000000e+00, -1.28522158e+00,
        -1.29942918e+00, -1.29060650e+00, -8.31801653e-01, -3.74819189e-01,
        -3.71078551e-01, -3.67159039e-01, -2.23462796e+00, -1.69319897e+01,
        -1.69674988e+01, -1.69676838e+01, -2.15084434e+00, -7.15083361e+00,
        -7.37936687e+00, -7.36868954e+00, -4.21329069e+00, -8.27718452e-02,
        -1.24796307e+00, -4.95824909e+00, -9.97292846e-02, -8.43439639e-01,
        -7.68151331e+00, -4.78676033e+01, -8.95808414e-02, -6.76395130e+00,
        -2.31452370e+01, -2.14822407e+01, -1.90461293e-01, -9.29418147e-01,
        -9.16560173e-01, -9.16304529e-01, -7.31199682e-02, -4.68080282e+00,
        -1.37990475e+01, -2.53613529e+01, -7.69328058e-01, -2.57231998e+01,
        -4.43504639e+01, -4.43504639e+01, -2.48892214e-02, -1.99578774e+00,
        -2.38156223e+00, -1.24971414e+00, -1.67597163e+00, -2.05126357e+00,
        -2.70510125e+00, -2.55365443e+00, -1.16673684e+00, -2.16948247e+00,
        -2.86512208e+00, -3.27024627e+00, -5.41437149e-01, -3.45802486e-01,
        -6.81373775e-01, -6.75405979e-01, -9.60106328e-02, -7.77658415e+00,
        -9.69930840e+00, -1.20210714e+01, -4.62343454e+00, -4.47822452e-01,
        -7.18827009e-01, -7.41441548e-01, -1.59148678e-01, -7.50997305e-01,
        -6.04152083e-01, -2.84954518e-01, -9.57863390e-01, -2.92718887e+00,
        -2.83756185e+00, -2.78898811e+00, -5.18779325e+00, -2.03206873e+00,
        -5.86123419e+00, -3.77449703e+00, -1.46375194e-01, -5.54890537e+00,
        -5.40770531e+00, -5.26774406e+00, -9.96078253e-01, -3.75033689e+00,
        -6.57310963e+00, -3.94640899e+00, -1.78797722e-01, -5.47335625e+00,
        -5.21668291e+00, -4.98719931e+00, -9.86756086e-01, -4.51958418e+00,
        -6.29521275e+00, -3.96570754e+00, -2.72345841e-01, -4.74249840e+00,
        -4.50498819e+00, -4.33115387e+00, -9.38890874e-01, -1.61851585e+00,
        -1.94192767e+00, -2.63493752e+00, -2.88199902e+00, -2.60975361e-01,
        -2.16639489e-01, -9.56084061e+00, -1.06103764e+01, -8.75149742e-02,
        -5.51771736e+01, -3.37559853e+01, -8.83310413e+00, -7.99549937e-01,
        -5.60008824e-01, -5.58068395e-01, -5.33924282e-01, -4.32770395e+00,
        -7.93437881e+01, -8.20649338e+01, -2.25568924e+01, -1.34809589e+00,
        -1.51718485e+00, -1.49551833e+00, -1.47510171e+00, -8.54948938e-01,
        -2.35689783e+00, -2.58576965e+00, -2.36979365e+00, -4.44492511e-02,
        -1.67383182e+00, -1.50726569e+00, -1.46057856e+00, -2.17201376e+00,
        -3.21458173e+00, -3.09007239e+00, -3.24794269e+00, -3.37522292e+00,
        -1.23717833e+00, -1.46405125e+00, -1.43231595e+00, -2.13025546e+00,
        -4.99080563e+00, -4.07025671e+00, -4.09021568e+00, -6.57141209e-02,
        -1.32839632e+00, -1.32517672e+00, -1.43224967e+00, -7.39378691e-01,
        -1.50103152e+00, -1.49142814e+00, -9.25668657e-01, -1.25993192e+00,
        -7.67816734e+00, -3.12934470e+00, -3.08731818e+00, -3.04504895e+00,
        -6.36989415e-01, -1.82449150e+00, -1.82776761e+00, -1.83045268e+00,
        -4.26480696e-02, -1.04434609e-01,  0.00000000e+00, -4.20163002e+01,
        -4.67293784e-02, -2.33135748e+00, -4.06357908e+00, -4.50624704e+00,
        -1.06608534e+00, -1.00651115e+02,  7.28000000e+02, -9.95272980e+01,
        -2.16815062e-02, -1.48802209e+00, -1.48474491e+00, -1.35374200e+00,
        -3.70563455e-02, -6.93542778e-01, -8.18431526e-02, -3.74847353e-02,
        -3.22635397e-02, -1.36441305e-01, -3.37151326e-02, -1.78695336e-01,
        -9.80581269e-02, -3.71836603e-01, -4.75990653e-01, -4.61997449e-01,
        -2.80533195e-01, -1.90043271e-01, -2.90260166e-01, -5.76969266e-01,
        -8.57090428e-02, -1.92506164e-01, -2.95091659e-01, -1.97454795e-01,
        -3.00736040e-01, -1.62213877e-01, -2.20604435e-01, -5.07222176e-01,
        -3.84288192e-01, -2.25349665e-01, -2.49517951e-02, -2.46122889e-02,
        -1.60867751e-01, -3.15893218e-02, -1.21019170e-01, -9.69805121e-02,
        -2.94235677e-01, -4.74155635e-01, -3.13581944e-01, -1.55290008e-01,
        -3.12243819e-01, -2.89008856e-01, -3.93194139e-01, -9.62433591e-02,
        -7.87413940e-02, -3.10176522e-01, -1.97383299e-01, -2.75928974e-01,
        -1.62117273e-01, -2.20691025e-01, -3.50649387e-01, -6.26690388e-01,
        -9.83115956e-02, -4.07214724e-02, -5.95556013e-02, -1.32881388e-01,
        -3.65375318e-02, -1.54320017e-01, -6.84934109e-02, -3.35891426e-01,
        -4.35091615e-01, -4.28386629e-01, -2.54415691e-01, -7.49172494e-02,
        -2.77414858e-01, -5.67019641e-01, -6.76125437e-02, -1.64723903e-01,
        -2.68129379e-01, -2.03935817e-01, -4.34157789e-01, -1.47973523e-01,
        -2.17688963e-01, -5.10301292e-01, -6.28516197e+00, -2.71663189e-01,
        -1.96912777e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00])}

In [ ]:
def assertion_bounds_final(bounds_final):
    return np.all(bounds_final["obs_min"] <= bounds_final["obs_max"])

In [ ]:
def get_bounds_continous():
    bounds_raw = load_bounds_raw()
    bounds_final = bounds_raw_to_bounds_final(bounds_raw)

    assert assertion_bounds_final(bounds_final)

    return {
        "raw": bounds_raw,
        "final": bounds_final,
    }

In [ ]:
bounds["continuous"] = get_bounds_continous()

In [ ]:
# np.save( os.path.join(dir_dataset["continuous"], f"obs_min.npy"), bounds["continuous"]["final"]["obs_min"], )
# np.save( os.path.join(dir_dataset["continuous"], f"obs_max.npy"), bounds["continuous"]["final"]["obs_max"], )

## Tabular

In [77]:
head_by_id(dataset["continuous"]["neural"]["final"], n=2)

,id,t,obs_init,obs,act,rew,obs_next,probs_init,probs,probs_next
0,20,0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[4.6153204e-07, 0.41843063, 0.09803962, 0.2416..."
1,20,1,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[4.6153204e-07, 0.41843063, 0.09803962, 0.2416...","[1.3341968e-18, 0.99022615, 0.0011949288, 0.00..."
2,20,2,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[1.3341968e-18, 0.99022615, 0.0011949288, 0.00...","[4.3437872e-23, 0.99479574, 5.7580583e-06, 0.0..."
3,20,3,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[4.3437872e-23, 0.99479574, 5.7580583e-06, 0.0...","[9.325621e-10, 0.00401068, 0.008864737, 0.9811..."
4,20,4,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[9.325621e-10, 0.00401068, 0.008864737, 0.9811...","[4.656923e-15, 6.592461e-05, 0.0002901405, 0.9..."
5,20,5,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[4.656923e-15, 6.592461e-05, 0.0002901405, 0.9...","[2.4188708e-07, 8.889674e-06, 0.00064626464, 0..."
6,20,6,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[2.4188708e-07, 8.889674e-06, 0.00064626464, 0...","[0.0, 1.0, 9.294034e-10, 3.452601e-08, 7.56487..."
7,20,7,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",1,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[0.0, 1.0, 9.294034e-10, 3.452601e-08, 7.56487...","[0.0, 1.0, 9.294034e-10, 3.452601e-08, 7.56487..."
8,25,0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",2,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[4.83073e-08, 7.87445e-06, 0.07960352, 0.91251...","[4.83073e-08, 7.87445e-06, 0.07960352, 0.91251...","[1.7647663e-11, 1.2354242e-06, 0.002096404, 0...."
9,25,1,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",2,1.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[4.83073e-08, 7.87445e-06, 0.07960352, 0.91251...","[1.7647663e-11, 1.2354242e-06, 0.002096404, 0....","[5.115847e-25, 0.00045865908, 0.0034875793, 0...."
10,25,2,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[-0.0800016, -0.08865834, -0.08860586, -0.0254...",3,0.0,"[-0.0800016, -0.08865834, -0.08860586, -0.0254...","[4.83073e-08, 7.87445e-06, 0.07960352, 0.91251...","[5.115847e-25, 0.00045865908, 0.0034875793, 0....","[5.115847e-25, 0.00045865908, 0.0034875793, 0...."

In [76]:
head_by_id(dataset["tabular"]["clustered_final"]["original"], n=2)

,id,t,obs_init,obs,act,rew,obs_next,probs_init,probs,probs_next,probs_behavior_init,probs_behavior,probs_behavior_next
0,20,0,58,58,1,0.0,179,"[0.016237022, 0.0014849559, 0.6178519, 0.30005...","[0.016237022, 0.0014849559, 0.6178519, 0.30005...","[0.0009460958, 0.98486024, 0.00033117103, 0.00...","[0.64220184, 0.09633028, 0.07798165, 0.1422018...","[0.64220184, 0.09633028, 0.07798165, 0.1422018...","[0.5987261, 0.18152866, 0.05732484, 0.10509554..."
1,20,1,58,179,1,0.0,17,"[0.016237022, 0.0014849559, 0.6178519, 0.30005...","[0.0009460958, 0.98486024, 0.00033117103, 0.00...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.64220184, 0.09633028, 0.07798165, 0.1422018...","[0.5987261, 0.18152866, 0.05732484, 0.10509554...","[0.64451313, 0.1576507, 0.038639877, 0.1112828..."
2,20,2,58,17,1,0.0,17,"[0.016237022, 0.0014849559, 0.6178519, 0.30005...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.64220184, 0.09633028, 0.07798165, 0.1422018...","[0.64451313, 0.1576507, 0.038639877, 0.1112828...","[0.64451313, 0.1576507, 0.038639877, 0.1112828..."
3,20,3,58,17,1,0.0,17,"[0.016237022, 0.0014849559, 0.6178519, 0.30005...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.64220184, 0.09633028, 0.07798165, 0.1422018...","[0.64451313, 0.1576507, 0.038639877, 0.1112828...","[0.64451313, 0.1576507, 0.038639877, 0.1112828..."
4,20,4,58,17,1,0.0,17,"[0.016237022, 0.0014849559, 0.6178519, 0.30005...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.64220184, 0.09633028, 0.07798165, 0.1422018...","[0.64451313, 0.1576507, 0.038639877, 0.1112828...","[0.64451313, 0.1576507, 0.038639877, 0.1112828..."
5,20,5,58,17,1,0.0,17,"[0.016237022, 0.0014849559, 0.6178519, 0.30005...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.64220184, 0.09633028, 0.07798165, 0.1422018...","[0.64451313, 0.1576507, 0.038639877, 0.1112828...","[0.64451313, 0.1576507, 0.038639877, 0.1112828..."
6,20,6,58,17,1,0.0,256,"[0.016237022, 0.0014849559, 0.6178519, 0.30005...","[0.002630175, 0.0006064938, 0.0013344456, 0.00...","[0.099401385, 0.08730502, 0.018886177, 0.36740...","[0.64220184, 0.09633028, 0.07798165, 0.1422018...","[0.64451313, 0.1576507, 0.038639877, 0.1112828...","[0.2, 0.2, 0.2, 0.2, 0.2]"
7,20,7,58,256,4,0.0,256,"[0.016237022, 0.0014849559, 0.6178519, 0.30005...","[0.099401385, 0.08730502, 0.018886177, 0.36740...","[0.099401385, 0.08730502, 0.018886177, 0.36740...","[0.64220184, 0.09633028, 0.07798165, 0.1422018...","[0.2, 0.2, 0.2, 0.2, 0.2]","[0.2, 0.2, 0.2, 0.2, 0.2]"
8,25,0,254,254,2,0.0,254,"[0.03472524, 0.033255864, 0.9320189, 0.0, 0.0]","[0.03472524, 0.033255864, 0.9320189, 0.0, 0.0]","[0.03472524, 0.033255864, 0.9320189, 0.0, 0.0]","[0.6666667, 0.16666667, 0.16666667, 0.0, 0.0]","[0.6666667, 0.16666667, 0.16666667, 0.0, 0.0]","[0.6666667, 0.16666667, 0.16666667, 0.0, 0.0]"
9,25,1,254,254,2,1.0,257,"[0.03472524, 0.033255864, 0.9320189, 0.0, 0.0]","[0.03472524, 0.033255864, 0.9320189, 0.0, 0.0]","[0.019111522, 0.31436116, 0.07228454, 0.422952...","[0.6666667, 0.16666667, 0.16666667, 0.0, 0.0]","[0.6666667, 0.16666667, 0.16666667, 0.0, 0.0]","[0.2, 0.2, 0.2, 0.2, 0.2]"
10,25,2,254,257,3,0.0,257,"[0.03472524, 0.033255864, 0.9320189, 0.0, 0.0]","[0.019111522, 0.31436116, 0.07228454, 0.422952...","[0.019111522, 0.31436116, 0.07228454, 0.422952...","[0.6666667, 0.16666667, 0.16666667, 0.0, 0.0]","[0.2, 0.2, 0.2, 0.2, 0.2]","[0.2, 0.2, 0.2, 0.2, 0.2]"

In [83]:
def get_dataset_hybrid(df_c, df_t):
    df = df_c.copy(deep=False)
    for label in ["obs_init", "obs", "obs_next"]:
        df[label] = df_t[label]

    return df

In [82]:
dataset["continuous"]["tabular"] = get_dataset_hybrid(
    dataset["continuous"]["neural"]["final"],
    dataset["tabular"]["clustered_final"]["original"],
)

In [84]:
head_by_id(dataset["continuous"]["tabular"], n=2)

,id,t,obs_init,obs,act,rew,obs_next,probs_init,probs,probs_next
0,20,0,58,58,1,0.0,179,"[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[4.6153204e-07, 0.41843063, 0.09803962, 0.2416..."
1,20,1,58,179,1,0.0,17,"[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[4.6153204e-07, 0.41843063, 0.09803962, 0.2416...","[1.3341968e-18, 0.99022615, 0.0011949288, 0.00..."
2,20,2,58,17,1,0.0,17,"[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[1.3341968e-18, 0.99022615, 0.0011949288, 0.00...","[4.3437872e-23, 0.99479574, 5.7580583e-06, 0.0..."
3,20,3,58,17,1,0.0,17,"[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[4.3437872e-23, 0.99479574, 5.7580583e-06, 0.0...","[9.325621e-10, 0.00401068, 0.008864737, 0.9811..."
4,20,4,58,17,1,0.0,17,"[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[9.325621e-10, 0.00401068, 0.008864737, 0.9811...","[4.656923e-15, 6.592461e-05, 0.0002901405, 0.9..."
5,20,5,58,17,1,0.0,17,"[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[4.656923e-15, 6.592461e-05, 0.0002901405, 0.9...","[2.4188708e-07, 8.889674e-06, 0.00064626464, 0..."
6,20,6,58,17,1,0.0,256,"[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[2.4188708e-07, 8.889674e-06, 0.00064626464, 0...","[0.0, 1.0, 9.294034e-10, 3.452601e-08, 7.56487..."
7,20,7,58,256,1,0.0,256,"[1.9520018e-30, 0.28778797, 0.007400115, 0.701...","[0.0, 1.0, 9.294034e-10, 3.452601e-08, 7.56487...","[0.0, 1.0, 9.294034e-10, 3.452601e-08, 7.56487..."
8,25,0,254,254,2,0.0,254,"[4.83073e-08, 7.87445e-06, 0.07960352, 0.91251...","[4.83073e-08, 7.87445e-06, 0.07960352, 0.91251...","[1.7647663e-11, 1.2354242e-06, 0.002096404, 0...."
9,25,1,254,254,2,1.0,257,"[4.83073e-08, 7.87445e-06, 0.07960352, 0.91251...","[1.7647663e-11, 1.2354242e-06, 0.002096404, 0....","[5.115847e-25, 0.00045865908, 0.0034875793, 0...."
10,25,2,254,257,3,0.0,257,"[4.83073e-08, 7.87445e-06, 0.07960352, 0.91251...","[5.115847e-25, 0.00045865908, 0.0034875793, 0....","[5.115847e-25, 0.00045865908, 0.0034875793, 0...."

In [88]:
dataset["continuous"]["tabular"].to_parquet(
    os.path.join(dir_policy["continuous"]["tabular"], "dataset.parquet")
)

# Common

In [440]:
onpe_continuous_primal = get_OnPV(dataset["continuous"]["primal"])
onpe_continuous_primal

0.013728592007028587

In [441]:
onpe_continuous_final = get_OnPV(dataset["continuous"]["final"])
onpe_continuous_final

0.013728592007028587

In [49]:
onpe_clustered_primal = get_OnPV(dataset["tabular"]["clustered_primal"]["test"])
onpe_clustered_primal

0.013728592007028587

In [50]:
onpe_clustered_final_original = get_OnPV(dataset["tabular"]["clustered_final"]["original"])
onpe_clustered_final_original

0.013728592007028587

In [51]:
onpe_clustered_final_exploratory = get_OnPV(dataset["tabular"]["clustered_final"]["exploratory"])
onpe_clustered_final_exploratory

0.017873921677523844

In [52]:
onpe_clustered_final_evaluation = get_OnPV(dataset["tabular"]["clustered_final"]["evaluation"])
onpe_clustered_final_evaluation

0.019905330552325445